#!/usr/bin/env python3
"""
REALISTIC SCRIMS - vertical promo trailer pipeline.

Builds a 1080x1920 / 60 fps H.264 + AAC trailer from two existing gameplay
videos of the Fortnite Creative map "Realistic Scrims" (map code 0674-0917-0977):

  --scrims    "fortnite new video scrims.mp4"  (35.26 s, 1080x1920, 60 fps)
  --timeline  "Timeline 1.mp4"                 (29.33 s, 1080x1920, 60 fps)

Everything else (sound effects, voice-over, motion graphics) is generated by
this script. There is deliberately NO music - the soundtrack is sound design:

  * SFX + bed    : synthesized from scratch with numpy/scipy (original work):
                   impacts, braams, whooshes, risers, heartbeat, kill-confirm
                   pings, explosion debris + tinnitus, rocket roar, UI blips
  * voice-over   : Piper TTS, voice "en_US-joe-medium" (CC0 dataset)
  * graphics     : rendered with Pillow using Anton (SIL OFL) and Inter Display

Pipeline:
  1. synthesize voice lines, process them (EQ, compression, de-ess, room)
  2. synthesize the sound-design layer, every effect cued to an on-screen event
  3. pull the original gameplay audio through the same time-map (only from
     windows where the creators' own narration is silent) and mix it in
  4. duck bed/SFX/game under the voice, loudness-normalise to -14 LUFS / -1.5 dBTP
  5. render video frame by frame (OpenCV): time-remapped source frames,
     speed ramps, freeze frame, punch-ins, shakes, whip blurs, flashes,
     colour grade, captions and the end card -> piped into libx264
  6. mux video + audio into the final MP4

Usage:
  python3 edit_trailer.py --scrims SRC1 --timeline SRC2 --voices VOICE_DIR \
      --out OUT_DIR --work WORK_DIR [--stills 0.5,3.2,...] [--audio-only]
"""
import argparse
import json
import math
import os
import subprocess
import sys
import wave

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont
from scipy import signal

W, H, FPS = 1080, 1920, 60
SR = 48000
BPM = 120
BEAT = 60.0 / BPM          # 0.5 s
STEP = BEAT / 4            # 16th note
TOTAL = 37.0               # trailer length (s)

MAP_NAME = "REALISTIC SCRIMS"
MAP_CODE = "0674-0917-0977"

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "assets")
FONT_ANTON = os.path.join(ASSETS, "fonts", "Anton-Regular.ttf")
FONT_INTER = "/usr/share/fonts/opentype/inter/InterDisplay-Black.otf"

# Palette (BGR for OpenCV, RGB for Pillow)
CYAN_RGB = (0, 229, 255)
ICE_RGB = (170, 245, 255)
WHITE_RGB = (255, 255, 255)
CYAN_BGR = (255, 229, 0)

# ----------------------------------------------------------------------------
# EDIT DECISION LIST
# keys: (output_time, source_time) pairs; piecewise-linear time remap.
# A flat pair (same source time twice) is a freeze frame.
# ----------------------------------------------------------------------------
SEGMENTS = [
    # --- HOOK -------------------------------------------------------------
    dict(name="A1 aim+shot", src="t1", keys=[(0.0, 12.62), (1.0, 13.38)]),
    dict(name="A2 elimination", src="t1", keys=[(1.0, 13.60), (3.0, 15.40)]),
    # --- MAP IDENTITY -------------------------------------------------------
    # source is letterboxed here (200 px bars) -> base zoom fills the frame
    dict(name="B spawn-in", src="sc", keys=[(3.0, 0.42), (5.0, 1.45)], zoom=1.27, dim=0.5, blur=True),
    dict(name="C weapon wall", src="sc", keys=[(5.0, 7.00), (7.0, 9.00)]),
    dict(name="D weapon pick", src="sc", keys=[(7.0, 10.00), (8.0, 11.00)]),
    dict(name="E gold ADS", src="sc", keys=[(8.0, 12.14), (9.0, 13.14)]),
    # --- ACTION MONTAGE -----------------------------------------------------
    dict(name="G build", src="t1", keys=[(9.0, 10.35), (11.0, 12.55)]),
    dict(name="H edit", src="t1", keys=[(11.0, 15.55), (12.5, 17.20)]),
    dict(name="I aim", src="sc", keys=[(12.5, 18.86), (13.5, 19.86)]),
    dict(name="J air fight", src="sc", keys=[(13.5, 15.05), (14.5, 16.15)]),
    dict(name="K elim freeze", src="sc", keys=[(14.5, 16.22), (14.85, 16.22), (16.5, 17.87)], freeze=(14.5, 14.85)),
    dict(name="V victory r4", src="sc", keys=[(16.5, 20.38), (17.5, 21.18)]),
    dict(name="L climb/edit", src="sc", keys=[(17.5, 21.50), (20.0, 24.00)]),
    dict(name="M rocket aim", src="sc", keys=[(20.0, 24.00), (21.0, 24.74)]),
    dict(name="N rocket flight", src="sc", keys=[(21.0, 24.76), (24.0, 27.95), (25.0, 28.68)]),
    # --- CLIMAX -------------------------------------------------------------
    dict(name="O explosion elim", src="sc", keys=[(25.0, 28.76), (25.9, 29.16), (27.5, 30.98)]),
    dict(name="P breathe", src="sc", keys=[(27.5, 31.34), (29.0, 32.56)]),
    dict(name="Q victory r8", src="sc", keys=[(29.0, 32.78), (31.0, 34.55)]),
    # --- END CARD (blurred real gameplay background) ------------------------
    dict(name="END card bg", src="sc", keys=[(31.0, 13.16), (37.0, 14.62)], endcard=True),
]

# Windows of each source where the creators' narration is silent
# (measured with Whisper). Original game audio is only used inside these.
GAME_AUDIO_WINDOWS = {
    "sc": [(13.30, 18.10), (19.00, 29.95)],
    "t1": [(10.40, 18.40)],
}

IMPACTS = [  # (time, strength)
    (0.0, 1.0), (1.0, 0.9), (3.0, 1.0), (9.0, 1.0), (14.5, 1.0),
    (17.5, 0.5), (21.0, 0.9), (25.0, 1.2), (29.0, 0.8), (31.0, 1.0), (36.0, 0.7),
]
WHIPS = [(5.0, 1), (7.0, -1), (8.0, 1), (11.0, -1), (12.5, 1), (13.5, -1), (16.5, 1),
         (20.0, -1), (27.5, 1)]
BEAT_BUMP_RANGES = []   # no music -> no beat pulses
RADIAL_HITS = [(3.0, 0.7), (21.0, 1.0), (25.0, 1.3), (31.0, 0.6)]

VO_LINES = [  # (start, text, length_scale)
    (0.15, "This is where your mechanics get tested.", 0.92),
    (3.10, "Jump into Realistic Scrims.", 0.95),
    (5.30, "No easy fights. No second chances.", 0.95),
    (9.05, "Build fast.", 0.95),
    (11.05, "Edit faster.", 0.95),
    (12.55, "Hit your shots.", 0.95),
    (16.55, "Every round brings a new challenge.", 0.92),
    (22.70, "Think you can dominate?", 0.95),
    (27.20, "Load up. Lock in.", 0.95),
    (28.55, "Prove yourself.", 0.97),
    (31.55, "Zero six seven four.", 0.9),
    (32.85, "Zero nine one seven.", 0.9),
    (34.15, "Zero nine seven seven.", 0.9),
]
# highlight each code group while it is read (replaced by measured VO
# placement from <work>/vo_placement.json when available)
CODE_GROUP_TIMES = [31.55, 32.85, 34.15]
CODE_GROUP_END = 35.6


def log(*a):
    print(*a, flush=True)


def run(cmd, **kw):
    r = subprocess.run(cmd, **kw)
    if r.returncode != 0:
        raise SystemExit(f"command failed ({r.returncode}): {' '.join(map(str, cmd))[:300]}")
    return r


# ============================================================================
# AUDIO HELPERS
# ============================================================================
def t_arr(dur):
    return np.arange(int(dur * SR)) / SR


def sos_filter(x, kind, freq, order=2):
    sos = signal.butter(order, freq, btype=kind, fs=SR, output="sos")
    return signal.sosfilt(sos, x, axis=0)


def peaking(x, f0, gain_db, q=1.0):
    a = 10 ** (gain_db / 40)
    w0 = 2 * math.pi * f0 / SR
    alpha = math.sin(w0) / (2 * q)
    b = [1 + alpha * a, -2 * math.cos(w0), 1 - alpha * a]
    aa = [1 + alpha / a, -2 * math.cos(w0), 1 - alpha / a]
    return signal.lfilter(np.array(b) / aa[0], np.array(aa) / aa[0], x, axis=0)


def add(buf, x, t0, gain=1.0, pan=0.0):
    """Mix mono/stereo x into stereo buf at time t0 with constant-power pan."""
    i0 = int(round(t0 * SR))
    if x.ndim == 1:
        l = math.cos((pan + 1) * math.pi / 4)
        r = math.sin((pan + 1) * math.pi / 4)
        x = np.stack([x * l * 1.414, x * r * 1.414], 1)
    if i0 < 0:
        x = x[-i0:]
        i0 = 0
    n = min(len(x), len(buf) - i0)
    if n > 0:
        buf[i0:i0 + n] += x[:n] * gain


def make_ir(dur=1.8, decay=0.45, seed=7, lp=6000):
    rng = np.random.default_rng(seed)
    t = t_arr(dur)
    ir = rng.standard_normal((len(t), 2)) * np.exp(-t / decay)[:, None]
    ir = sos_filter(ir, "lowpass", lp)
    ir[: int(0.012 * SR)] *= np.linspace(0, 1, int(0.012 * SR))[:, None]
    return ir / np.sqrt((ir ** 2).sum(0, keepdims=True))


def reverb(x, ir, wet):
    if x.ndim == 1:
        x = np.stack([x, x], 1)
    y = np.stack([signal.fftconvolve(x[:, c], ir[:, c])[: len(x)] for c in range(2)], 1)
    return x * (1 - wet) + y * wet


def env_ar(n, a, r):
    e = np.ones(n)
    na, nr = int(a * SR), int(r * SR)
    if na:
        e[:na] = np.linspace(0, 1, na)
    if nr:
        e[-nr:] *= np.linspace(1, 0, nr)
    return e


def midi_hz(m):
    return 440.0 * 2 ** ((m - 69) / 12)


# ----------------------------------------------------------------------------
# Instruments / SFX (all original synthesis)
# ----------------------------------------------------------------------------
RNG = np.random.default_rng(1234)


def riser(dur, f0=200, f1=2400):
    t = t_arr(dur)
    p = t / dur
    n = RNG.standard_normal((len(t), 2))
    out = np.zeros_like(n)
    hop = 2048
    for i in range(0, len(t), hop):          # time-varying bandpass in blocks
        fc = f0 * (f1 / f0) ** p[i]
        seg = n[max(0, i - 512): i + hop]
        y = sos_filter(seg, "bandpass", [fc * 0.6, min(fc * 1.8, 20000)])
        out[i: i + hop] = y[-len(out[i: i + hop]):]
    tone_f = 110 * 2 ** (3 * p)
    tone = np.sin(2 * np.pi * np.cumsum(tone_f) / SR) * 0.25
    e = p ** 2.2
    return (out * 0.9 + tone[:, None]) * e[:, None] * 0.7


def reverse_cymbal(dur):
    t = t_arr(dur)
    n = sos_filter(RNG.standard_normal((len(t), 2)), "highpass", 4000)
    return n * ((t / dur) ** 3)[:, None] * 0.45


def whoosh(dur=0.35, up=True):
    t = t_arr(dur)
    p = t / dur
    n = RNG.standard_normal((len(t), 2))
    out = np.zeros_like(n)
    hop = 1024
    for i in range(0, len(t), hop):
        q = p[i] if up else 1 - p[i]
        fc = 300 * (12 ** q)
        seg = n[max(0, i - 512): i + hop]
        y = sos_filter(seg, "bandpass", [fc * 0.5, min(fc * 2.0, 20000)])
        out[i: i + hop] = y[-len(out[i: i + hop]):]
    e = np.sin(np.pi * p) ** 1.5
    return out * e[:, None] * 0.8


def impact(strength=1.0):
    t = t_arr(2.4)
    f = 32 + 60 * np.exp(-t / 0.08)
    sub = np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t / 0.7)
    crack = sos_filter(RNG.standard_normal(len(t)), "lowpass", 5000) * np.exp(-t / 0.05)
    metal = sum(np.sin(2 * np.pi * fr * t) * np.exp(-t / d) for fr, d in
                ((313, 0.5), (487, 0.35), (811, 0.25), (1273, 0.18))) * 0.12
    x = np.tanh(1.5 * (sub * 1.0 + crack * 0.7 + metal)) * 0.9
    return x * strength


def text_hit():
    t = t_arr(0.18)
    n = sos_filter(RNG.standard_normal(len(t)), "bandpass", [1500, 9000]) * np.exp(-t / 0.02)
    thump = np.sin(2 * np.pi * (70 + 120 * np.exp(-t / 0.02)) * t) * np.exp(-t / 0.06)
    return (n * 0.5 + thump * 0.6) * 0.6


def blip(f=1800):
    t = t_arr(0.05)
    return np.sin(2 * np.pi * f * t) * np.exp(-t / 0.012) * 0.25


# ----------------------------------------------------------------------------
# Sound design (no music) - every element synthesized here, cued to picture
# ----------------------------------------------------------------------------
def band_sweep(dur, f0, f1, env, width=(0.6, 1.8), hop=1024):
    """Stereo noise through a band-pass whose centre glides f0 -> f1 (log)."""
    n = int(dur * SR)
    p = np.arange(n) / n
    noise = RNG.standard_normal((n, 2))
    out = np.zeros_like(noise)
    for i in range(0, n, hop):
        fc = f0 * (f1 / f0) ** p[i]
        seg = noise[max(0, i - 512): i + hop]
        y = sos_filter(seg, "bandpass", [max(20, fc * width[0]), min(fc * width[1], 20000)])
        out[i: i + hop] = y[-len(out[i: i + hop]):]
    return out * env(p)[:, None]


def swish(dur=0.2):
    return band_sweep(dur, 1500, 9000, lambda p: np.sin(np.pi * p) ** 2) * 0.8


def heartbeat(strength=1.0):
    t = t_arr(0.6)
    x = np.zeros(len(t))
    for d, a in ((0.0, 1.0), (0.17, 0.7)):
        tt = np.clip(t - d, 0, None)
        f = 42 + 45 * np.exp(-tt / 0.03)
        x += (t >= d) * np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-tt / 0.08) * a
    return np.tanh(2 * x) * 0.9 * strength


def braam(dur=2.2, f=55.0):
    """Low cinematic 'braam' hit: detuned saw cluster through an opening/closing low-pass."""
    t = t_arr(dur)
    x = sum(signal.sawtooth(2 * np.pi * ff * t + RNG.uniform(0, 6))
            for ff in (f, f * 1.007, f * 0.993, 2 * f * 1.003, 2 * f * 0.996))
    x = np.tanh(1.8 * x / 3)
    out = np.zeros(len(t))
    hop = 1024
    for i in range(0, len(t), hop):
        fc = 250 + 2200 * math.exp(-t[i] / 0.35) * min(t[i] / 0.03, 1)
        y = sos_filter(x[max(0, i - 1024): i + hop], "lowpass", fc)
        out[i: i + hop] = y[-len(out[i: i + hop]):]
    return out * np.minimum(t / 0.025, 1) * np.exp(-t / 0.9) * 0.9


def hit_confirm():
    """Bright metallic 'kill confirmed' ping."""
    t = t_arr(0.6)
    x = sum(np.sin(2 * np.pi * f * t) * np.exp(-t / d) * a
            for f, d, a in ((2350, 0.22, 0.5), (3525, 0.15, 0.35), (4700, 0.1, 0.25), (1175, 0.3, 0.25)))
    click = sos_filter(RNG.standard_normal(len(t)), "highpass", 3000) * np.exp(-t / 0.004) * 0.4
    return (x + click) * 0.6


def tinnitus(dur, f=3700):
    t = t_arr(dur)
    return np.sin(2 * np.pi * f * t) * np.minimum(t / 0.08, 1) * np.exp(-t / (dur * 0.45)) * 0.12


def debris(dur=1.8, count=55):
    n = int(dur * SR)
    x = np.zeros(n)
    for _ in range(count):
        t0 = RNG.exponential(dur * 0.25)
        if t0 > dur - 0.05:
            continue
        L = int(RNG.uniform(0.004, 0.03) * SR)
        i0 = int(t0 * SR)
        burst = RNG.standard_normal(L) * np.exp(-np.arange(L) / (L / 4))
        x[i0:i0 + L] += burst[: n - i0] * math.exp(-t0 / (dur * 0.4)) * RNG.uniform(0.3, 1)
    return sos_filter(x, "bandpass", [800, 7000]) * 0.7


def metal_click(f1=1900, f2=3100):
    t = t_arr(0.12)
    n = sos_filter(RNG.standard_normal(len(t)), "bandpass", [1500, 8000]) * np.exp(-t / 0.006)
    r = (np.sin(2 * np.pi * f1 * t) * 0.5 + np.sin(2 * np.pi * f2 * t) * 0.35) * np.exp(-t / 0.035)
    return (n * 0.8 + r) * 0.6


def weapon_rack():
    x = np.zeros(int(0.35 * SR))
    a, b = metal_click(), metal_click(1250, 2150)
    x[:len(a)] += a
    i = int(0.15 * SR)
    x[i:i + len(b)] += b * 1.1
    return x


def scope_whirr():
    t = t_arr(0.3)
    p = t / 0.3
    servo = sos_filter(signal.square(2 * np.pi * np.cumsum(500 + 900 * p) / SR) * 0.15, "bandpass", [400, 3000])
    air = sos_filter(RNG.standard_normal(len(t)), "bandpass", [1000, 5000]) * 0.2
    x = (servo + air) * np.sin(np.pi * p) ** 0.8
    c = metal_click(2600, 4100)
    x[-len(c):] += c * 0.8          # lock-on click
    return x


def glitch_sparkle(dur, density=70):
    """Digital materialise: random bit-crushed blips + sample-and-hold noise."""
    n = int(dur * SR)
    out = np.zeros((n, 2))
    for _ in range(int(density * dur)):
        t0 = RNG.uniform(0, max(dur - 0.07, 0.01))
        L = int(RNG.uniform(0.012, 0.05) * SR)
        tt = np.arange(L) / SR
        s = np.sin(2 * np.pi * RNG.uniform(1800, 7500) * tt) * np.exp(-tt / (L / SR / 3))
        if RNG.random() < 0.35:
            s = np.round(s * 3) / 3
        pan = RNG.uniform(-0.8, 0.8)
        i0 = int(t0 * SR)
        seg = out[i0:i0 + L]
        seg[:, 0] += s[:len(seg)] * math.cos((pan + 1) * math.pi / 4)
        seg[:, 1] += s[:len(seg)] * math.sin((pan + 1) * math.pi / 4)
    sh = sos_filter(np.repeat(RNG.uniform(-1, 1, n // 24 + 1), 24)[:n], "highpass", 2000) * 0.15
    gate = np.repeat(RNG.random(n // 2400 + 1), 2400)[:n] > 0.55
    out += (sh * gate)[:, None]
    p = np.arange(n) / n
    return out * (np.minimum(p / 0.1, 1) * (1 - p) ** 0.7)[:, None] * 0.35


def shimmer(dur=1.2):
    n = int(dur * SR)
    t = np.arange(n) / SR
    x = sos_filter(RNG.standard_normal((n, 2)), "bandpass", [6000, 14000])
    out = x * (np.minimum(t / 0.05, 1) * np.exp(-t / 0.35))[:, None] * 0.35
    sp = glitch_sparkle(dur * 0.8, 40)
    out[:len(sp)] += sp * 1.2
    return out


def tick(high=True):
    t = t_arr(0.06)
    n = sos_filter(RNG.standard_normal(len(t)), "bandpass", [3000, 9000]) * np.exp(-t / 0.002)
    tone = np.sin(2 * np.pi * (2900 if high else 2200) * t) * np.exp(-t / 0.012)
    return (n * 0.6 + tone * 0.5) * 0.5


def ui_confirm():
    x = np.zeros(int(0.2 * SR))
    a, b = blip(990), blip(1480)
    x[:len(a)] += a * 2
    i = int(0.07 * SR)
    x[i:i + len(b)] += b * 2.2
    return x


def suck(dur=0.35):
    """Reverse 'inhale' into a hit."""
    t = t_arr(dur)
    p = t / dur
    x = sos_filter(RNG.standard_normal((len(t), 2)), "bandpass", [400, 7000])
    sub = np.sin(2 * np.pi * np.cumsum(30 + 60 * p) / SR)[:, None] * 0.5
    return (x * 0.6 + sub) * (p ** 3)[:, None] * 0.8


def launch_blast():
    a = impact(1.0)
    w = band_sweep(1.4, 3500, 250, lambda p: (1 - p) ** 1.5 * np.minimum(p / 0.02, 1))
    x = np.zeros((max(len(a), len(w)), 2))
    x[:len(a)] += a[:, None]
    x[:len(w)] += w * 0.9
    return x


def engine_roar(dur):
    n = int(dur * SR)
    p = np.arange(n) / n
    w = band_sweep(dur, 260, 900, lambda p: 0.25 + 0.75 * p ** 1.5, width=(0.5, 2.5))
    rum = sos_filter(RNG.standard_normal(n), "lowpass", 90)
    rum = rum / np.abs(rum).max() * (0.3 + 0.7 * p)
    return w * 0.6 + rum[:, None] * 0.5


def ambience_bed():
    """Non-musical air/rumble bed so the cut never drops into dead silence."""
    n = int(TOTAL * SR)
    t = np.arange(n) / SR
    w = np.cumsum(RNG.standard_normal((n, 2)), 0)
    w = sos_filter(sos_filter(w, "highpass", 25), "lowpass", 420)
    w /= np.abs(w).max()
    rum = sos_filter(RNG.standard_normal((n, 2)), "lowpass", 70)
    rum /= np.abs(rum).max()
    mod = (0.65 + 0.35 * np.sin(2 * np.pi * 0.11 * t) * np.sin(2 * np.pi * 0.037 * t + 1))[:, None]
    bed = w * mod + rum * 0.6
    bed *= 0.05 / np.sqrt((bed ** 2).mean())
    keys = [(0, 0.5), (2.9, 0.8), (3.0, 0.35), (8.9, 0.4), (9.0, 0.65), (17.5, 0.7), (20.8, 0.85), (21.0, 0.6), (24.8, 1.0),
            (24.85, 0.0), (25.0, 0.0), (25.05, 0.7), (27.5, 0.6), (28.0, 0.85), (29, 0.45),
            (31, 0.5), (36, 0.45), (TOTAL, 0.0)]
    g = np.interp(t, [k[0] for k in keys], [k[1] for k in keys])
    return bed * g[:, None]


def build_sound_design():
    n = int(TOTAL * SR)
    fx = np.zeros((n, 2))

    def A(x, t0, g=1.0, pan=0.0):
        add(fx, x, t0, g, pan)

    for ti, s in IMPACTS:
        A(impact(s), ti, 0.6)
    # HOOK: shot -> kill confirm -> heartbeat -> inhale into the title
    A(text_hit(), 0.12, 0.55)
    A(hit_confirm(), 1.04, 0.55)
    A(heartbeat(0.8), 1.62)
    A(heartbeat(0.9), 2.25)
    A(riser(1.4), 1.55, 0.5)
    A(suck(0.3), 2.65, 0.7)
    # TITLE: braam + digital spawn-in
    A(braam(2.4), 3.0, 0.42)
    A(glitch_sparkle(1.5), 3.08, 0.55)
    A(swish(), 5.08, 0.5, -0.3)
    A(weapon_rack(), 8.05, 0.8, 0.2)
    A(riser(1.3), 7.7, 0.65)
    A(reverse_cymbal(0.6), 8.4, 0.35)
    # MONTAGE
    for ti, d in WHIPS:
        A(whoosh(0.34, up=d > 0), ti - 0.21, 0.6, 0.45 * d)
    for ti in (9.04, 11.04, 28.52):       # AIM uses the scope lock-on click instead
        A(text_hit(), ti, 0.6)
    A(scope_whirr(), 12.22, 0.8)            # lock-on lands on the cut, clear of "Hit"
    A(suck(0.25), 14.25, 0.7)              # time-stop freeze
    A(hit_confirm(), 14.52, 0.5)
    A(tinnitus(0.9), 14.55, 1.0)
    A(swish(), 14.82, 0.5, 0.4)            # time resumes
    A(shimmer(1.3), 16.5, 0.9)             # VICTORY round 4
    A(reverse_cymbal(0.8), 16.7, 0.4)
    # suspense clock over the climb, accelerating into the launch
    ti, gap, k = 17.6, 0.5, 0
    while ti < 20.95:
        A(tick(k % 2 == 0), ti, 0.5 + 0.5 * (ti - 17.6) / 3.35, 0.15 if k % 2 else -0.15)
        gap = 0.5 if ti < 19.0 else (0.25 if ti < 20.3 else 0.125)
        ti += gap
        k += 1
    # ROCKET: launch -> roar + accelerating heartbeat -> inhale -> explosion
    A(riser(3.3), 17.7, 0.5)                # long build from the climb into the launch
    A(launch_blast(), 21.0, 0.75)
    A(debris(0.8), 21.05, 0.35, -0.4)
    A(engine_roar(3.85), 21.0, 0.4)
    A(riser(3.8), 21.05, 0.55)
    for k, ti in enumerate([21.55, 22.25, 22.85, 23.35, 23.78, 24.12, 24.4, 24.62]):
        A(heartbeat(0.6 + 0.05 * k), ti)
    A(suck(0.32), 24.53, 0.8)
    A(braam(2.0, 41.2), 25.0, 0.45)
    A(debris(2.0), 25.02, 0.6, -0.5)
    A(debris(2.0), 25.06, 0.6, 0.5)
    A(hit_confirm(), 25.12, 0.45)
    A(tinnitus(1.6, 3500), 25.12, 1.0)
    A(suck(0.35), 25.6, 0.45)              # speed ramp back to real time
    A(reverse_cymbal(0.7), 28.3, 0.35)
    A(shimmer(1.5), 29.0, 0.9)             # VICTORY round 8
    A(riser(1.6), 29.4, 0.6)
    A(reverse_cymbal(0.8), 30.2, 0.45)
    # END CARD
    A(braam(2.6, 49.0), 31.0, 0.5)
    for i in range(len(MAP_CODE)):
        A(blip(1600 + 90 * i), 31.62 + i * 0.028, 0.5, -0.6 + 1.2 * i / len(MAP_CODE))
    A(ui_confirm(), 32.3, 0.6)
    A(suck(0.4), 35.6, 0.6)
    fx = reverb(fx, make_ir(), 0.16)
    return ambience_bed(), fx


# ----------------------------------------------------------------------------
# Voice-over
# ----------------------------------------------------------------------------
def read_wav_mono(path):
    with wave.open(path) as w:
        sr = w.getframerate()
        a = np.frombuffer(w.readframes(w.getnframes()), np.int16).astype(np.float64) / 32768
        if w.getnchannels() == 2:
            a = a.reshape(-1, 2).mean(1)
    return a, sr


def trim_silence(a, thr=0.012, pad_s=0.03):
    idx = np.where(np.abs(a) > thr)[0]
    if not len(idx):
        return a
    p = int(pad_s * SR)
    return a[max(0, idx[0] - p): idx[-1] + p]


def compress(x, thr_db=-20, ratio=3.0, att=0.004, rel=0.09, makeup_db=0):
    """Feed-forward peak compressor (one-pole release follower)."""
    thr = 10 ** (thr_db / 20)
    er = math.exp(-1 / (rel * SR))
    env = signal.lfilter([1 - er], [1, -er], np.abs(x))
    env = np.maximum(env, 1e-9)
    gain = np.where(env > thr, (thr * (env / thr) ** (1 / ratio)) / env, 1.0)
    return x * gain * 10 ** (makeup_db / 20)


def deess(x, lo=5000, hi=10000, thr_db=-30, ratio=4.0):
    band = sos_filter(x, "bandpass", [lo, hi], 2)
    rest = x - band
    return rest + compress(band, thr_db, ratio, 0.001, 0.04)


def process_vo(a):
    a = sos_filter(a, "highpass", 85)
    a = peaking(a, 220, -2.0, 1.0)       # clear mud
    a = peaking(a, 3200, 3.0, 0.9)       # presence
    a = peaking(a, 110, 1.5, 0.8)        # a bit of chest
    a = compress(a, -22, 3.0, 0.004, 0.1)
    a = deess(a)
    a = np.tanh(a * 1.3) / np.tanh(1.3)  # gentle saturation
    return a / (np.abs(a).max() + 1e-9) * 0.89


def synth_vo(voices_dir, work):
    from piper import PiperVoice, SynthesisConfig
    model = os.path.join(voices_dir, "en_US-joe-medium.onnx")
    voice = PiperVoice.load(model)
    vo_dir = os.path.join(work, "vo")
    os.makedirs(vo_dir, exist_ok=True)
    track = np.zeros(int(TOTAL * SR))
    placed = []
    prev_end = 0.0
    for i, (t0, text, ls) in enumerate(VO_LINES):
        p = os.path.join(vo_dir, f"line_{i:02d}.wav")
        with wave.open(p, "wb") as w:
            voice.synthesize_wav(text, w, syn_config=SynthesisConfig(
                length_scale=ls, noise_scale=0.6, noise_w_scale=0.7))
        a, sr = read_wav_mono(p)
        a = signal.resample_poly(a, SR // math.gcd(SR, sr), sr // math.gcd(SR, sr))
        a = trim_silence(a)
        a = process_vo(a)
        dur = len(a) / SR
        if t0 < prev_end + 0.05:
            log(f"  WARN VO line {i} overlaps previous ({t0:.2f} < {prev_end:.2f}), shifting")
            t0 = prev_end + 0.05
        i0 = int(t0 * SR)
        track[i0:i0 + len(a)] += a[: len(track) - i0]
        placed.append(dict(start=round(t0, 3), end=round(t0 + dur, 3), text=text))
        prev_end = t0 + dur
        log(f"  VO {t0:6.2f}-{t0 + dur:6.2f}  {text}")
    # subtle room
    st = reverb(track, make_ir(0.6, 0.12, seed=3, lp=7000), 0.07)
    return st, placed


# ----------------------------------------------------------------------------
# Original gameplay audio, remapped with the same EDL
# ----------------------------------------------------------------------------
def load_src_audio(path):
    raw = run(["ffmpeg", "-v", "error", "-i", path, "-vn", "-ac", "2", "-ar", str(SR),
               "-f", "f32le", "-"], capture_output=True).stdout
    return np.frombuffer(raw, np.float32).reshape(-1, 2).astype(np.float64)


def seg_map(seg, t):
    ks = seg["keys"]
    return np.interp(t, [k[0] for k in ks], [k[1] for k in ks])


def game_audio(srcs):
    out = np.zeros((int(TOTAL * SR), 2))
    for seg in SEGMENTS:
        if seg.get("endcard"):
            continue
        a0, a1 = seg["keys"][0][0], seg["keys"][-1][0]
        i0, i1 = int(a0 * SR), int(a1 * SR)
        t = np.arange(i0, i1) / SR
        st = seg_map(seg, t)
        src = srcs[seg["src"]]
        idx = st * SR
        y = np.stack([np.interp(idx, np.arange(len(src)), src[:, c]) for c in range(2)], 1)
        # gain: inside narration-free windows only, muted on freeze frames
        g = np.zeros(len(t))
        for w0, w1 in GAME_AUDIO_WINDOWS[seg["src"]]:
            g = np.maximum(g, np.clip(np.minimum(st - w0, w1 - st) / 0.06, 0, 1))
        rate = np.gradient(st) * SR
        g *= np.clip(rate / 0.3, 0, 1)
        n = len(t)
        f = min(int(0.012 * SR), n // 2)
        g[:f] *= np.linspace(0, 1, f)
        g[-f:] *= np.linspace(1, 0, f)
        out[i0:i1] += y * g[:, None]
    return out


def envelope(x, att=0.03, rel=0.3):
    lvl = np.abs(x).max(1) if x.ndim == 2 else np.abs(x)
    ea, er = math.exp(-1 / (att * SR)), math.exp(-1 / (rel * SR))
    env = np.zeros_like(lvl)
    e = 0.0
    # decimated follower for speed
    hop = 64
    for i in range(0, len(lvl), hop):
        v = lvl[i:i + hop].max()
        c = ea ** hop if v > e else er ** hop
        e = c * e + (1 - c) * v
        env[i:i + hop] = e
    return env


def ffmpeg_write_wav(x, path, codec="pcm_s24le"):
    x = np.ascontiguousarray(x.astype(np.float32))
    run(["ffmpeg", "-v", "error", "-y", "-f", "f32le", "-ar", str(SR), "-ac", str(x.shape[1] if x.ndim == 2 else 1),
         "-i", "-", "-c:a", codec, path], input=x.tobytes())


def build_audio(args, work, out_dir):
    log("[audio] voice-over")
    vo, placed = synth_vo(args.voices, work)
    log("[audio] sound design (no music)")
    bed, sfx = build_sound_design()
    log("[audio] gameplay audio")
    srcs = {"sc": load_src_audio(args.scrims), "t1": load_src_audio(args.timeline)}
    game = game_audio(srcs)
    game = sos_filter(game, "highpass", 60)
    # shell-shock: muffle game audio while the explosion plays in slow motion
    i0, i1 = int(25.0 * SR), int(25.95 * SR)
    muff = sos_filter(game[i0 - 2048:i1], "lowpass", 550, 2)[2048:]
    xf = np.ones(i1 - i0)
    xf[-int(0.2 * SR):] = np.linspace(1, 0, int(0.2 * SR))
    game[i0:i1] = muff * xf[:, None] + game[i0:i1] * (1 - xf[:, None])

    # duck bed / sfx / game under narration
    env = envelope(vo, 0.02, 0.35)
    env = env / (env.max() + 1e-9)
    k = np.clip(env * 3.0, 0, 1)
    duck_bed = 1.0 - 0.6 * k
    duck_fx = 1.0 - 0.6 * k          # ~ -8 dB: keeps every line on top of the hits
    duck_g = 1.0 - 0.5 * k

    bed_m = bed * duck_bed[:, None]
    sfx_m = sfx * 0.7 * duck_fx[:, None]
    game_m = game * 2.0 * duck_g[:, None]
    vo_m = vo * 1.25
    mix = bed_m + sfx_m + game_m + vo_m
    # final tail fade
    nf = int(0.35 * SR)
    mix[-nf:] *= np.linspace(1, 0, nf)[:, None] ** 2
    # soft bus clip safety before loudnorm
    mix = np.tanh(mix * 0.9) / 0.9

    ffmpeg_write_wav(vo, os.path.join(out_dir, "voiceover.wav"))
    pre = os.path.join(work, "mix_pre.wav")
    ffmpeg_write_wav(mix, pre, "pcm_f32le")
    for name, stem in (("stem_bed.wav", bed_m), ("stem_sfx.wav", sfx_m),
                       ("stem_game.wav", game_m), ("stem_vo.wav", vo_m)):
        ffmpeg_write_wav(stem, os.path.join(work, name), "pcm_f32le")
    ffmpeg_write_wav(sfx * 0.7, os.path.join(ASSETS, "sfx_layer.wav"), "pcm_s16le")
    ffmpeg_write_wav(bed, os.path.join(ASSETS, "ambience_bed.wav"), "pcm_s16le")

    # two-pass loudnorm -> -14 LUFS, -1.5 dBTP
    r = subprocess.run(["ffmpeg", "-hide_banner", "-i", pre, "-af",
                        "loudnorm=I=-14:TP=-1.5:LRA=11:print_format=json", "-f", "null", "-"],
                       capture_output=True, text=True)
    js = json.loads(r.stderr[r.stderr.rfind("{"): r.stderr.rfind("}") + 1])
    af = ("loudnorm=I=-14:TP=-1.5:LRA=11:linear=true:"
          f"measured_I={js['input_i']}:measured_TP={js['input_tp']}:measured_LRA={js['input_lra']}:"
          f"measured_thresh={js['input_thresh']}:offset={js['target_offset']},"
          "alimiter=limit=0.76:attack=3:release=40:level=false")
    final = os.path.join(out_dir, "final_audio.wav")
    run(["ffmpeg", "-v", "error", "-y", "-i", pre, "-af", af, "-ar", str(SR), "-c:a", "pcm_s24le", final])
    with open(os.path.join(work, "vo_placement.json"), "w") as f:
        json.dump(placed, f, indent=1)
    return final, placed


# ============================================================================
# GRAPHICS
# ============================================================================
def font(path, size):
    return ImageFont.truetype(path, size)


def text_width(fnt, text, tracking):
    w = 0
    for i, ch in enumerate(text):
        w += fnt.getlength(ch) + (tracking if i < len(text) - 1 else 0)
    return w


def render_lines(lines, max_w=920, gap=0.02, glow=True):
    """lines: [(text, rgb, size, font_path, tracking)] -> BGRA numpy image"""
    rendered = []
    for text, rgb, size, fpath, tr in lines:
        fnt = font(fpath, size)
        tw = text_width(fnt, text, tr)
        if tw > max_w:  # auto-fit
            size = int(size * max_w / tw)
            fnt = font(fpath, size)
            tw = text_width(fnt, text, tr)
        asc, desc = fnt.getmetrics()
        rendered.append((text, rgb, size, fnt, tr, tw, asc + desc))
    pad = 60
    bw = int(max(r[5] for r in rendered)) + pad * 2
    bh = int(sum(r[6] for r in rendered) * (1 + gap)) + pad * 2
    mask_fill = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
    mask_all = Image.new("L", (bw, bh), 0)
    d = ImageDraw.Draw(mask_fill)
    dm = ImageDraw.Draw(mask_all)
    y = pad
    for text, rgb, size, fnt, tr, tw, lh in rendered:
        x = (bw - tw) / 2
        for ch in text:
            d.text((x, y), ch, font=fnt, fill=rgb + (255,))
            dm.text((x, y), ch, font=fnt, fill=255)
            x += fnt.getlength(ch) + tr
        y += lh * (1 + gap)
    base = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
    # drop shadow
    sh = mask_all.filter(ImageFilter.GaussianBlur(10))
    shadow = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
    shadow.putalpha(sh.point(lambda v: int(v * 0.85)))
    base = Image.alpha_composite(base, shadow)
    if glow:
        g = mask_all.filter(ImageFilter.GaussianBlur(18))
        glow_l = Image.new("RGBA", (bw, bh), CYAN_RGB + (0,))
        glow_l.putalpha(g.point(lambda v: int(v * 0.55)))
        base = Image.alpha_composite(base, glow_l)
    base = Image.alpha_composite(base, mask_fill)
    arr = np.array(base)
    return arr[..., [2, 1, 0, 3]].copy()  # RGBA -> BGRA


def gradient_band(h=760, strength=0.62):
    y = np.linspace(-1, 1, h)
    a = (1 - np.abs(y) ** 2) * strength
    img = np.zeros((h, W, 4), np.uint8)
    img[..., 3] = (a[:, None] * 255).astype(np.uint8)
    img[..., :3] = (8, 6, 4)
    return img


def rounded_panel(w, h, r, fill_rgba, border_rgb=None, bw=4, glow=True):
    pad = 50
    im = Image.new("RGBA", (w + 2 * pad, h + 2 * pad), (0, 0, 0, 0))
    if glow and border_rgb:
        g = Image.new("L", im.size, 0)
        ImageDraw.Draw(g).rounded_rectangle([pad, pad, pad + w, pad + h], r, outline=255, width=bw + 6)
        g = g.filter(ImageFilter.GaussianBlur(16))
        gl = Image.new("RGBA", im.size, border_rgb + (0,))
        gl.putalpha(g.point(lambda v: int(v * 0.8)))
        im = Image.alpha_composite(im, gl)
    layer = Image.new("RGBA", im.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    d.rounded_rectangle([pad, pad, pad + w, pad + h], r, fill=fill_rgba,
                        outline=(border_rgb + (255,)) if border_rgb else None, width=bw)
    im = Image.alpha_composite(im, layer)
    arr = np.array(im)
    return arr[..., [2, 1, 0, 3]].copy()


def hline(w, thickness=4, rgb=CYAN_RGB):
    pad = 30
    im = Image.new("RGBA", (w + 2 * pad, thickness + 2 * pad), (0, 0, 0, 0))
    g = Image.new("L", im.size, 0)
    ImageDraw.Draw(g).rectangle([pad, pad, pad + w, pad + thickness], fill=255)
    gb = g.filter(ImageFilter.GaussianBlur(8))
    gl = Image.new("RGBA", im.size, rgb + (0,))
    gl.putalpha(gb)
    im = Image.alpha_composite(im, gl)
    solid = Image.new("RGBA", im.size, rgb + (0,))
    solid.putalpha(g)
    im = Image.alpha_composite(im, solid)
    arr = np.array(im)
    return arr[..., [2, 1, 0, 3]].copy()


def ease_out(x):
    x = min(max(x, 0.0), 1.0)
    return 1 - (1 - x) ** 3


def ease_out_back(x, s=1.6):
    x = min(max(x, 0.0), 1.0) - 1
    return 1 + (s + 1) * x ** 3 + s * x ** 2


class Overlay:
    def __init__(self, img, cx, cy, t0, t1, anim="slam", scale0=1.35, fade_out=0.12,
                 wipe=0.0, delay_alpha=0.06, pulse=False, slide=0, scale_x_anim=False, shine=None):
        self.img, self.cx, self.cy, self.t0, self.t1 = img, cx, cy, t0, t1
        self.anim, self.scale0, self.fade_out, self.wipe = anim, scale0, fade_out, wipe
        self.delay_alpha, self.pulse, self.slide, self.scale_x_anim = delay_alpha, pulse, slide, scale_x_anim
        self.shine = shine  # (start, duration) of a light sweep across the glyphs

    def draw(self, frame, t):
        if not (self.t0 <= t < self.t1):
            return
        u, r = t - self.t0, self.t1 - t
        alpha = min(u / self.delay_alpha, 1.0) if self.delay_alpha > 0 else 1.0
        if self.fade_out > 0:
            alpha *= min(r / self.fade_out, 1.0)
        sx = sy = 1.0
        dx = 0.0
        if self.anim == "slam":
            s = 1 + (self.scale0 - 1) * (1 - ease_out(u / 0.16))
            sx = sy = s
        elif self.anim == "pop":
            s = 0.6 + 0.4 * ease_out_back(u / 0.28)
            sx = sy = s
        elif self.anim == "slide":
            dx = self.slide * (1 - ease_out(u / 0.3))
        if self.scale_x_anim:
            sx = max(0.02, ease_out(u / 0.4))
            sy = 1.0
        if r < self.fade_out:  # tiny push on exit
            k = 1 + 0.06 * (1 - r / self.fade_out)
            sx *= k
            sy *= k
        if self.pulse:
            ph = ((t - self.t0) % BEAT) / BEAT
            k = 1 + 0.035 * math.exp(-ph * 6)
            sx *= k
            sy *= k
        img = self.img
        if self.wipe > 0:
            frac = ease_out(u / self.wipe)
            cut = int(img.shape[1] * frac)
            img = img.copy()
            img[:, cut:, 3] = 0
        if self.shine and 0 <= (t - self.shine[0]) / self.shine[1] <= 1:
            img = apply_shine(img, (t - self.shine[0]) / self.shine[1])
        if abs(sx - 1) > 1e-3 or abs(sy - 1) > 1e-3:
            nw, nh = max(2, int(img.shape[1] * sx)), max(2, int(img.shape[0] * sy))
            img = cv2.resize(img, (nw, nh), interpolation=cv2.INTER_LINEAR)
        blit(frame, img, self.cx + dx, self.cy, alpha)


def apply_shine(img, p):
    """Diagonal light band sweeping left->right, masked by the graphic's own alpha."""
    h, w = img.shape[:2]
    cx = -0.25 * w + p * 1.5 * w
    d = (np.arange(w)[None, :] - cx) + 0.35 * (np.arange(h)[:, None] - h / 2)
    wgt = np.exp(-(d / (0.07 * w)) ** 2) * (img[..., 3] / 255.0) * 0.75
    out = img.astype(np.float32)
    out[..., :3] += (255 - out[..., :3]) * wgt[..., None]
    return out.astype(np.uint8)


def blit(frame, img, cx, cy, alpha=1.0):
    h, w = img.shape[:2]
    x0, y0 = int(round(cx - w / 2)), int(round(cy - h / 2))
    fx0, fy0 = max(0, x0), max(0, y0)
    fx1, fy1 = min(W, x0 + w), min(H, y0 + h)
    if fx1 <= fx0 or fy1 <= fy0 or alpha <= 0:
        return
    sub = img[fy0 - y0: fy1 - y0, fx0 - x0: fx1 - x0]
    a = sub[..., 3:4].astype(np.float32) * (alpha / 255.0)
    roi = frame[fy0:fy1, fx0:fx1].astype(np.float32)
    frame[fy0:fy1, fx0:fx1] = (roi * (1 - a) + sub[..., :3].astype(np.float32) * a).astype(np.uint8)


def build_overlays():
    A, I = FONT_ANTON, FONT_INTER
    ov = []
    save = {}
    LOW = 1330   # lower-third caption centre (inside TikTok/Reels safe zone)
    band = gradient_band()

    HIGH = 560   # upper third: keeps the in-game "ELIMINATED" banner (y~1330) visible
    def caption(lines, t0, t1, anim="slam", cy=LOW, **kw):
        img = render_lines(lines)
        ov.append(Overlay(band, W / 2, cy, t0, t1, anim="fade", delay_alpha=0.1, fade_out=0.15))
        ov.append(Overlay(img, W / 2, cy, t0, t1, anim=anim, **kw))
        return img

    save["caption_think_youre_ready"] = caption(
        [("THINK YOU'RE", WHITE_RGB, 118, A, 4), ("READY?", CYAN_RGB, 200, A, 6)], 0.12, 2.92, cy=HIGH)
    # title reveal
    title = render_lines([("REALISTIC", CYAN_RGB, 176, A, 10), ("SCRIMS", WHITE_RGB, 300, A, 12)])
    save["title_realistic_scrims"] = title
    ov.append(Overlay(title, W / 2, 900, 3.0, 4.95, anim="slam", scale0=1.6, fade_out=0.18, shine=(3.25, 0.55)))
    bar = hline(760, 5)
    ov.append(Overlay(bar, W / 2, 620, 3.05, 4.95, anim="fade", scale_x_anim=True, fade_out=0.18))
    ov.append(Overlay(bar, W / 2, 1190, 3.05, 4.95, anim="fade", scale_x_anim=True, fade_out=0.18))
    save["caption_tagline"] = caption(
        [("YOUR MECHANICS.", WHITE_RGB, 104, A, 4), ("YOUR TEST.", CYAN_RGB, 150, A, 6)], 5.12, 8.92,
        anim="slide", slide=-90, delay_alpha=0.18)
    for word, t0, t1, cy in (("BUILD.", 9.04, 10.94, LOW), ("EDIT.", 11.04, 12.44, LOW),
                             ("AIM.", 12.54, 13.44, LOW), ("ELIMINATE.", 14.50, 15.75, HIGH)):
        save[f"caption_{word.strip('.').lower()}"] = caption([(word, WHITE_RGB, 210, A, 8)], t0, t1,
                                                             cy=cy, scale0=1.5)
    save["caption_prove_yourself"] = caption(
        [("PROVE", WHITE_RGB, 150, A, 6), ("YOURSELF.", CYAN_RGB, 190, A, 8)], 28.52, 30.92, scale0=1.5)

    # ---- END CARD ----
    e_title = render_lines([("REALISTIC", CYAN_RGB, 160, A, 10), ("SCRIMS", WHITE_RGB, 270, A, 12)])
    save["endcard_title"] = e_title
    ov.append(Overlay(e_title, W / 2, 640, 31.0, TOTAL + 1, anim="slam", scale0=1.5, fade_out=0, shine=(31.4, 0.6)))
    label = render_lines([("MAP CODE", ICE_RGB, 58, I, 14)], glow=False)
    save["endcard_label"] = label
    ov.append(Overlay(label, W / 2, 990, 31.35, TOTAL + 1, anim="slide", slide=0, delay_alpha=0.2, fade_out=0))
    l2 = hline(200, 4)
    ov.append(Overlay(l2, W / 2 - 330, 992, 31.35, TOTAL + 1, anim="fade", scale_x_anim=True, fade_out=0))
    ov.append(Overlay(l2, W / 2 + 330, 992, 31.35, TOTAL + 1, anim="fade", scale_x_anim=True, fade_out=0))
    panel = rounded_panel(960, 200, 28, (6, 10, 16, 215), CYAN_RGB, 5)
    save["endcard_code_panel"] = panel
    ov.append(Overlay(panel, W / 2, 1140, 31.5, TOTAL + 1, anim="pop", fade_out=0, delay_alpha=0.1))
    code = render_lines([(MAP_CODE, WHITE_RGB, 150, A, 6)], max_w=880, glow=True)
    save["endcard_code"] = code
    ov.append(Overlay(code, W / 2, 1140, 31.62, TOTAL + 1, anim="fade", wipe=0.38, delay_alpha=0.01, fade_out=0,
                      shine=(32.25, 0.6)))
    btn = rounded_panel(560, 140, 70, CYAN_RGB + (255,), CYAN_RGB, 2)
    btn_txt = render_lines([("PLAY NOW", (5, 12, 20), 100, A, 8)], glow=False)
    bh, bw = btn_txt.shape[:2]
    comb = btn.copy()
    blit_rgba(comb, btn_txt)
    save["endcard_play_now"] = comb
    ov.append(Overlay(comb, W / 2, 1440, 32.3, TOTAL + 1, anim="pop", fade_out=0, delay_alpha=0.1, pulse=True,
                      shine=(33.3, 0.5)))
    return ov, save


def blit_rgba(dst, src):
    """alpha-composite src (BGRA) centred onto dst (BGRA), in place."""
    h, w = src.shape[:2]
    H2, W2 = dst.shape[:2]
    y0, x0 = (H2 - h) // 2, (W2 - w) // 2
    ys, xs = max(0, -y0), max(0, -x0)
    y0c, x0c = max(0, y0), max(0, x0)
    sub = src[ys: ys + min(h, H2), xs: xs + min(w, W2)]
    hh, ww = sub.shape[:2]
    hh, ww = min(hh, H2 - y0c), min(ww, W2 - x0c)
    sub = sub[:hh, :ww].astype(np.float32)
    d = dst[y0c:y0c + hh, x0c:x0c + ww].astype(np.float32)
    a = sub[..., 3:4] / 255
    rgb = sub[..., :3] * a + d[..., :3] * (1 - a)
    al = sub[..., 3:4] + d[..., 3:4] * (1 - a)
    dst[y0c:y0c + hh, x0c:x0c + ww] = np.concatenate([rgb, al], 2).astype(np.uint8)


# ============================================================================
# VIDEO
# ============================================================================
class SegmentFrames:
    def __init__(self, path, t_lo, t_hi):
        ss = max(0.0, math.floor(t_lo * FPS - 2) / FPS)
        dur = (t_hi - ss) + 3 / FPS
        raw = run(["ffmpeg", "-v", "error", "-ss", f"{ss:.4f}", "-i", path, "-t", f"{dur:.4f}",
                   "-vf", "scale=in_color_matrix=bt709:in_range=tv:out_range=pc,format=bgr24",
                   "-f", "rawvideo", "-pix_fmt", "bgr24", "-"], capture_output=True).stdout
        self.frames = np.frombuffer(raw, np.uint8).reshape(-1, H, W, 3)
        self.first = int(math.ceil(ss * FPS - 1e-6))

    def get(self, t_src, blend):
        f = t_src * FPS - self.first
        n = len(self.frames)
        i0 = int(math.floor(f))
        frac = f - i0
        i0 = min(max(i0, 0), n - 1)
        if not blend or frac < 0.08 or i0 + 1 >= n:
            j = min(max(int(round(f)), 0), n - 1)
            return self.frames[j].copy()
        return cv2.addWeighted(self.frames[i0], 1 - frac, self.frames[i0 + 1], frac, 0)


def make_grade_lut():
    x = np.arange(256) / 255.0
    s = x * x * (3 - 2 * x)
    base = x * 0.62 + s * 0.38                      # contrast
    sh = (1 - x) ** 2.2
    b = np.clip(base + 0.035 * sh, 0, 1)            # cool shadows
    g = np.clip(base + 0.008 * sh, 0, 1)
    r = np.clip(base - 0.025 * sh, 0, 1)
    return [(c * 255).astype(np.uint8) for c in (b, g, r)]


def make_vignette(strength=0.30):
    yy, xx = np.mgrid[0:H, 0:W]
    d = np.sqrt(((xx - W / 2) / (W / 2)) ** 2 * 0.8 + ((yy - H / 2) / (H / 2)) ** 2)
    v = 1 - strength * np.clip(d - 0.45, 0, None) ** 1.6
    v = np.clip(v, 0, 1)
    return np.repeat((v * 255).astype(np.uint8)[..., None], 3, 2)


def decay(t, t0, dur):
    if t < t0 or t >= t0 + dur:
        return 0.0
    return math.exp(-4.5 * (t - t0) / dur)


def radial_blur(frame, amount, taps=5):
    acc = frame.astype(np.float32)
    for i in range(1, taps + 1):
        M = cv2.getRotationMatrix2D((W / 2, H / 2), 0, 1 + amount * i / taps)
        acc += cv2.warpAffine(frame, M, (W, H), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT101)
    return (acc / (taps + 1)).astype(np.uint8)


def shake_xy(t, amp):
    return (amp * (math.sin(t * 91.3) * 0.6 + math.sin(t * 57.1 + 1.3) * 0.4),
            amp * (math.sin(t * 77.7 + 0.7) * 0.6 + math.sin(t * 43.9 + 2.1) * 0.4))


def render_video(args, work, out_video, stills=None):
    lut = make_grade_lut()
    vig = make_vignette()
    overlays, saved = build_overlays()
    gfx_dir = os.path.join(ASSETS, "graphics")
    os.makedirs(gfx_dir, exist_ok=True)
    for k, im in saved.items():
        cv2.imwrite(os.path.join(gfx_dir, f"{k}.png"), im)

    paths = {"sc": args.scrims, "t1": args.timeline}
    code_times, code_end = CODE_GROUP_TIMES, CODE_GROUP_END
    vp = os.path.join(work, "vo_placement.json")
    if os.path.exists(vp):
        with open(vp) as f:
            placed = json.load(f)
        code_times = [p["start"] for p in placed[-3:]]
        code_end = placed[-1]["end"] + 0.25
    cut_times = sorted({s["keys"][0][0] for s in SEGMENTS})
    impact_t = {t for t, _ in IMPACTS}

    enc = None
    if stills is None:
        enc = subprocess.Popen([
            "ffmpeg", "-v", "error", "-y", "-f", "rawvideo", "-pix_fmt", "bgr24", "-s", f"{W}x{H}",
            "-r", str(FPS), "-i", "-",
            "-vf", "scale=in_range=pc:out_color_matrix=bt709:out_range=tv,format=yuv420p",
            "-c:v", "libx264", "-preset", "slow", "-crf", "18", "-maxrate", "16M", "-bufsize", "32M",
            "-profile:v", "high", "-level", "4.2", "-g", "60", "-bf", "2",
            "-color_primaries", "bt709", "-color_trc", "bt709", "-colorspace", "bt709", "-color_range", "tv",
            "-movflags", "+faststart", out_video], stdin=subprocess.PIPE)

    nframes = int(round(TOTAL * FPS))
    frames_wanted = None
    if stills is not None:
        frames_wanted = {int(round(s * FPS)): s for s in stills}
    cache = {}
    for n in range(nframes):
        t = n / FPS
        if frames_wanted is not None and n not in frames_wanted:
            continue
        si = max(i for i, s in enumerate(SEGMENTS) if s["keys"][0][0] <= t + 1e-9)
        seg = SEGMENTS[si]
        if si not in cache:
            cache.clear()
            ks = seg["keys"]
            cache[si] = SegmentFrames(paths[seg["src"]], min(k[1] for k in ks), max(k[1] for k in ks))
        st = float(seg_map(seg, t))
        st_next = float(seg_map(seg, t + 1 / FPS))
        rate = (st_next - st) * FPS
        frame = cache[si].get(st, blend=(0.05 < rate < 0.92))
        seg_t0, seg_t1 = seg["keys"][0][0], seg["keys"][-1][0]
        u = (t - seg_t0) / (seg_t1 - seg_t0)

        # ---- camera: zoom / punch / shake / rotation ----
        z = seg.get("zoom", 1.0) * (1.0 + 0.035 * u)     # slow push-in per shot
        amp = 0.0
        rot = 0.0
        for ti, s in IMPACTS:
            k = decay(t, ti, 0.4)
            z += 0.09 * s * k
            amp += 16 * s * decay(t, ti, 0.32)
            rot += 0.6 * s * decay(t, ti, 0.3) * math.sin(t * 60)
        for ct in cut_times:
            if ct not in impact_t:
                z += 0.045 * decay(t, ct, 0.22)
        for a0, a1 in BEAT_BUMP_RANGES:
            if a0 <= t < a1:
                ph = ((t - a0) % BEAT)
                z += 0.014 * math.exp(-ph / 0.07)
        if seg.get("endcard"):
            z = 1.06 + 0.05 * u
        dx, dy = shake_xy(t, amp)
        z = max(z, 1.0 + 2 * (abs(dx) + abs(dy)) / W + 0.004)
        M = cv2.getRotationMatrix2D((W / 2, H / 2), rot, z)
        M[0, 2] += dx
        M[1, 2] += dy
        frame = cv2.warpAffine(frame, M, (W, H), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT101)
        for ti, s_ in RADIAL_HITS:
            k = decay(t, ti, 0.14)
            if k > 0.05:
                frame = radial_blur(frame, 0.09 * s_ * k)

        # ---- whip transitions: directional motion blur around cuts ----
        for wt, d in WHIPS:
            dt = t - wt
            if -0.05 <= dt < 0.05:
                k = 1 - abs(dt + 0.5 / FPS) / 0.05
                L = int(10 + 110 * max(k, 0))
                ker = np.zeros((1, L), np.float32)
                ker[0, :] = 1.0 / L
                frame = cv2.filter2D(frame, -1, ker)
                shift = int(d * 70 * max(k, 0) * (1 if dt < 0 else -1))
                frame = np.roll(frame, shift, axis=1)

        # ---- grade ----
        b, g, r = cv2.split(frame)
        frame = cv2.merge([cv2.LUT(b, lut[0]), cv2.LUT(g, lut[1]), cv2.LUT(r, lut[2])])
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray3 = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
        sat = 1.12
        if seg.get("freeze") and seg["freeze"][0] <= t < seg["freeze"][1]:
            sat = 0.55
        frame = cv2.addWeighted(frame, sat, gray3, 1 - sat, 0)
        if seg.get("freeze") and seg["freeze"][0] <= t < seg["freeze"][1]:
            tint = np.full_like(frame, CYAN_BGR)
            frame = cv2.addWeighted(frame, 0.86, tint, 0.14, 0)

        if not seg.get("endcard"):  # gentle unsharp mask for crisper detail on phones
            soft = cv2.GaussianBlur(frame, (0, 0), 1.3)
            frame = cv2.addWeighted(frame, 1.4, soft, -0.4, 0)

        # ---- section looks ----
        if "dim" in seg:
            k = min((t - seg_t0) / 0.25, 1.0) * min((seg_t1 - t) / 0.2, 1.0)
            if seg.get("blur"):  # soften busy background under the title
                small = cv2.resize(frame, (W // 3, H // 3), interpolation=cv2.INTER_AREA)
                soft = cv2.resize(cv2.GaussianBlur(small, (0, 0), 3), (W, H), interpolation=cv2.INTER_LINEAR)
                frame = cv2.addWeighted(frame, 1 - 0.85 * k, soft, 0.85 * k, 0)
            frame = cv2.convertScaleAbs(frame, alpha=1 - (1 - seg["dim"]) * k)
        if seg.get("endcard"):
            small = cv2.resize(frame, (W // 4, H // 4), interpolation=cv2.INTER_AREA)
            small = cv2.GaussianBlur(small, (0, 0), 5)
            frame = cv2.resize(small, (W, H), interpolation=cv2.INTER_LINEAR)
            frame = cv2.convertScaleAbs(frame, alpha=0.42)
            # cyan radial glow behind the code
            if "glow" not in cache:
                yy, xx = np.mgrid[0:H, 0:W]
                gl = np.exp(-(((xx - W / 2) / 520) ** 2 + ((yy - 1140) / 300) ** 2))
                cache["glow"] = (gl[..., None] * np.array(CYAN_BGR, np.float32) * 0.22).astype(np.uint8)
            pulse = 0.75 + 0.25 * math.exp(-((t - 31.0) % BEAT) / 0.12)
            frame = cv2.add(frame, (cache["glow"] * pulse).astype(np.uint8))

        frame = cv2.multiply(frame, vig, scale=1 / 255)

        # ---- chromatic aberration on impacts ----
        ca = max([decay(t, ti, 0.14) * s for ti, s in IMPACTS if ti > 0] + [0])  # clean first frame
        if ca > 0.05:
            sh = int(10 * ca)
            b, g, r = cv2.split(frame)
            frame = cv2.merge([np.roll(b, -sh, 1), g, np.roll(r, sh, 1)])

        # ---- overlays ----
        for o in overlays:
            o.draw(frame, t)
        # code-group highlight under each group as the VO reads it
        if t >= code_times[0] - 0.05 and t < code_end:
            gi = max(i for i, gt in enumerate(code_times) if t >= gt - 0.05)
            centers = [W / 2 - 300, W / 2, W / 2 + 300]
            x0 = int(centers[gi] - 120)
            g0 = max(code_times[gi] - 0.05, 31.95)  # wait until the digits have wiped in
            if t < g0:
                k = 0.0
            else:
                k = min((t - g0) / 0.12, 1.0)
            if k > 0:
                cv2.rectangle(frame, (x0, 1212), (x0 + int(240 * k), 1220), CYAN_BGR, -1)

        # ---- flashes ----
        fl = max([decay(t, ti, 0.16) * s for ti, s in IMPACTS if ti > 0] + [0])
        if fl > 0.02:
            col = np.full_like(frame, 255)
            col[..., 0] = 255
            col[..., 1] = 245
            col[..., 2] = 225
            frame = cv2.addWeighted(frame, 1 - 0.55 * min(fl, 1), col, 0.55 * min(fl, 1), 0)
        # cut-to-black at the very end
        if t > TOTAL - 0.3:
            frame = cv2.convertScaleAbs(frame, alpha=max(0.0, (TOTAL - t) / 0.3))

        if enc:
            enc.stdin.write(frame.tobytes())
        else:
            cv2.imwrite(os.path.join(work, f"still_{t:06.2f}.png"), frame)
        if n % 120 == 0:
            log(f"  frame {n}/{nframes}  t={t:5.2f}  [{seg['name']}]")
    if enc:
        enc.stdin.close()
        if enc.wait() != 0:
            raise SystemExit("encoder failed")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scrims", required=True, help='"fortnite new video scrims.mp4"')
    ap.add_argument("--timeline", required=True, help='"Timeline 1.mp4"')
    ap.add_argument("--voices", required=True, help="dir containing en_US-joe-medium.onnx(+.json)")
    ap.add_argument("--out", default=HERE)
    ap.add_argument("--work", required=True, help="temp dir for intermediates")
    ap.add_argument("--stills", default=None, help="comma list of times: only render PNG stills")
    ap.add_argument("--audio-only", action="store_true")
    args = ap.parse_args()
    os.makedirs(args.work, exist_ok=True)
    os.makedirs(args.out, exist_ok=True)

    if args.stills:
        render_video(args, args.work, None, [float(s) for s in args.stills.split(",")])
        return
    final_audio, placed = build_audio(args, args.work, args.out)
    if args.audio_only:
        return
    vid = os.path.join(args.work, "video_only.mp4")
    log("[video] rendering")
    render_video(args, args.work, vid)
    out = os.path.join(args.out, "realistic_scrims_trailer.mp4")
    log("[mux]")
    run(["ffmpeg", "-v", "error", "-y", "-i", vid, "-i", final_audio, "-map", "0:v:0", "-map", "1:a:0",
         "-c:v", "copy", "-c:a", "aac", "-b:a", "256k", "-ar", str(SR), "-ac", "2",
         "-movflags", "+faststart", "-shortest", out])
    log("done:", out)


if __name__ == "__main__":
    main()
