#!/usr/bin/env python3
"""
REALISTIC SCRIMS - vertical promo trailer pipeline.

Builds a 1080x1920 / 60 fps H.264 + AAC trailer from two existing gameplay
videos of the Fortnite Creative map "Realistic Scrims" (map code 0674-0917-0977):

  --scrims    "fortnite new video scrims.mp4"  (35.26 s, 1080x1920, 60 fps)
  --timeline  "Timeline 1.mp4"                 (29.33 s, 1080x1920, 60 fps)

Everything else (music, sound effects, voice-over, motion graphics) is
generated by this script:

  * music + SFX  : synthesized from scratch with numpy/scipy (original work)
  * voice-over   : Piper TTS, voice "en_US-joe-medium" (CC0 dataset)
  * graphics     : rendered with Pillow using Anton (SIL OFL) and Inter Display

Pipeline:
  1. synthesize voice lines, process them (EQ, compression, de-ess, room)
  2. synthesize the music/SFX score on a 120 BPM grid that matches the cuts
  3. pull the original gameplay audio through the same time-map (only from
     windows where the creators' own narration is silent) and mix it in
  4. duck music under the voice, loudness-normalise to -14 LUFS / -1 dBTP
  5. render video frame by frame (OpenCV): time-remapped source frames,
     speed ramps, freeze frame, punch-ins, shakes, whip blurs, flashes,
     colour grade, captions and the end card -> piped into libx264
  6. mux video + audio into the final MP4

Usage:
  python3 edit_trailer.py --scrims SRC1 --timeline SRC2 --voices VOICE_DIR \
      --out OUT_DIR --work WORK_DIR [--stills 0.5,3.2,...] [--audio-only]
"""
import argparse
import json
import math
import os
import subprocess
import sys
import wave

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont
from scipy import signal

W, H, FPS = 1080, 1920, 60
SR = 48000
BPM = 120
BEAT = 60.0 / BPM          # 0.5 s
STEP = BEAT / 4            # 16th note
TOTAL = 37.0               # trailer length (s)

MAP_NAME = "REALISTIC SCRIMS"
MAP_CODE = "0674-0917-0977"

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "assets")
FONT_ANTON = os.path.join(ASSETS, "fonts", "Anton-Regular.ttf")
FONT_INTER = "/usr/share/fonts/opentype/inter/InterDisplay-Black.otf"

# Palette (BGR for OpenCV, RGB for Pillow)
CYAN_RGB = (0, 229, 255)
ICE_RGB = (170, 245, 255)
WHITE_RGB = (255, 255, 255)
CYAN_BGR = (255, 229, 0)

# ----------------------------------------------------------------------------
# EDIT DECISION LIST
# keys: (output_time, source_time) pairs; piecewise-linear time remap.
# A flat pair (same source time twice) is a freeze frame.
# ----------------------------------------------------------------------------
SEGMENTS = [
    # --- HOOK -------------------------------------------------------------
    dict(name="A1 aim+shot", src="t1", keys=[(0.0, 12.62), (1.0, 13.38)]),
    dict(name="A2 elimination", src="t1", keys=[(1.0, 13.60), (3.0, 15.40)]),
    # --- MAP IDENTITY -------------------------------------------------------
    # source is letterboxed here (200 px bars) -> base zoom fills the frame
    dict(name="B spawn-in", src="sc", keys=[(3.0, 0.42), (5.0, 1.45)], zoom=1.27, dim=0.5, blur=True),
    dict(name="C weapon wall", src="sc", keys=[(5.0, 7.00), (7.0, 9.00)]),
    dict(name="D weapon pick", src="sc", keys=[(7.0, 10.00), (8.0, 11.00)]),
    dict(name="E gold ADS", src="sc", keys=[(8.0, 12.14), (9.0, 13.14)]),
    # --- ACTION MONTAGE -----------------------------------------------------
    dict(name="G build", src="t1", keys=[(9.0, 10.35), (11.0, 12.55)]),
    dict(name="H edit", src="t1", keys=[(11.0, 15.55), (12.5, 17.20)]),
    dict(name="I aim", src="sc", keys=[(12.5, 18.86), (13.5, 19.86)]),
    dict(name="J air fight", src="sc", keys=[(13.5, 15.05), (14.5, 16.15)]),
    dict(name="K elim freeze", src="sc", keys=[(14.5, 16.22), (14.85, 16.22), (16.5, 17.87)], freeze=(14.5, 14.85)),
    dict(name="V victory r4", src="sc", keys=[(16.5, 20.38), (17.5, 21.18)]),
    dict(name="L climb/edit", src="sc", keys=[(17.5, 21.50), (20.0, 24.00)]),
    dict(name="M rocket aim", src="sc", keys=[(20.0, 24.00), (21.0, 24.74)]),
    dict(name="N rocket flight", src="sc", keys=[(21.0, 24.76), (24.0, 27.95), (25.0, 28.68)]),
    # --- CLIMAX -------------------------------------------------------------
    dict(name="O explosion elim", src="sc", keys=[(25.0, 28.76), (25.9, 29.16), (27.5, 30.98)]),
    dict(name="P breathe", src="sc", keys=[(27.5, 31.34), (29.0, 32.56)]),
    dict(name="Q victory r8", src="sc", keys=[(29.0, 32.78), (31.0, 34.55)]),
    # --- END CARD (blurred real gameplay background) ------------------------
    dict(name="END card bg", src="sc", keys=[(31.0, 13.16), (37.0, 14.62)], endcard=True),
]

# Windows of each source where the creators' narration is silent
# (measured with Whisper). Original game audio is only used inside these.
GAME_AUDIO_WINDOWS = {
    "sc": [(13.30, 18.10), (19.00, 29.95)],
    "t1": [(10.40, 18.40)],
}

IMPACTS = [  # (time, strength)
    (0.0, 1.0), (1.0, 0.9), (3.0, 1.0), (9.0, 1.0), (14.5, 1.0),
    (17.5, 0.5), (21.0, 0.9), (25.0, 1.2), (29.0, 0.8), (31.0, 1.0), (36.0, 0.7),
]
WHIPS = [(5.0, 1), (7.0, -1), (8.0, 1), (11.0, -1), (12.5, 1), (13.5, -1), (16.5, 1),
         (20.0, -1), (27.5, 1)]
BEAT_BUMP_RANGES = [(9.0, 16.5), (17.5, 21.0), (25.0, 27.5), (29.0, 31.0)]

VO_LINES = [  # (start, text, length_scale)
    (0.15, "This is where your mechanics get tested.", 0.92),
    (3.10, "Jump into Realistic Scrims.", 0.95),
    (5.30, "No easy fights. No second chances.", 0.95),
    (9.05, "Build fast.", 0.95),
    (11.05, "Edit faster.", 0.95),
    (12.55, "Hit your shots.", 0.95),
    (16.55, "Every round brings a new challenge.", 0.92),
    (22.70, "Think you can dominate?", 0.95),
    (27.20, "Load up. Lock in.", 0.95),
    (28.55, "Prove yourself.", 0.97),
    (31.55, "Zero six seven four.", 0.9),
    (32.85, "Zero nine one seven.", 0.9),
    (34.15, "Zero nine seven seven.", 0.9),
]
# highlight each code group while it is read (replaced by measured VO
# placement from <work>/vo_placement.json when available)
CODE_GROUP_TIMES = [31.55, 32.85, 34.15]
CODE_GROUP_END = 35.6


def log(*a):
    print(*a, flush=True)


def run(cmd, **kw):
    r = subprocess.run(cmd, **kw)
    if r.returncode != 0:
        raise SystemExit(f"command failed ({r.returncode}): {' '.join(map(str, cmd))[:300]}")
    return r


# ============================================================================
# AUDIO HELPERS
# ============================================================================
def t_arr(dur):
    return np.arange(int(dur * SR)) / SR


def sos_filter(x, kind, freq, order=2):
    sos = signal.butter(order, freq, btype=kind, fs=SR, output="sos")
    return signal.sosfilt(sos, x, axis=0)


def peaking(x, f0, gain_db, q=1.0):
    a = 10 ** (gain_db / 40)
    w0 = 2 * math.pi * f0 / SR
    alpha = math.sin(w0) / (2 * q)
    b = [1 + alpha * a, -2 * math.cos(w0), 1 - alpha * a]
    aa = [1 + alpha / a, -2 * math.cos(w0), 1 - alpha / a]
    return signal.lfilter(np.array(b) / aa[0], np.array(aa) / aa[0], x, axis=0)


def add(buf, x, t0, gain=1.0, pan=0.0):
    """Mix mono/stereo x into stereo buf at time t0 with constant-power pan."""
    i0 = int(round(t0 * SR))
    if x.ndim == 1:
        l = math.cos((pan + 1) * math.pi / 4)
        r = math.sin((pan + 1) * math.pi / 4)
        x = np.stack([x * l * 1.414, x * r * 1.414], 1)
    if i0 < 0:
        x = x[-i0:]
        i0 = 0
    n = min(len(x), len(buf) - i0)
    if n > 0:
        buf[i0:i0 + n] += x[:n] * gain


def make_ir(dur=1.8, decay=0.45, seed=7, lp=6000):
    rng = np.random.default_rng(seed)
    t = t_arr(dur)
    ir = rng.standard_normal((len(t), 2)) * np.exp(-t / decay)[:, None]
    ir = sos_filter(ir, "lowpass", lp)
    ir[: int(0.012 * SR)] *= np.linspace(0, 1, int(0.012 * SR))[:, None]
    return ir / np.sqrt((ir ** 2).sum(0, keepdims=True))


def reverb(x, ir, wet):
    if x.ndim == 1:
        x = np.stack([x, x], 1)
    y = np.stack([signal.fftconvolve(x[:, c], ir[:, c])[: len(x)] for c in range(2)], 1)
    return x * (1 - wet) + y * wet


def env_ar(n, a, r):
    e = np.ones(n)
    na, nr = int(a * SR), int(r * SR)
    if na:
        e[:na] = np.linspace(0, 1, na)
    if nr:
        e[-nr:] *= np.linspace(1, 0, nr)
    return e


def midi_hz(m):
    return 440.0 * 2 ** ((m - 69) / 12)


# ----------------------------------------------------------------------------
# Instruments / SFX (all original synthesis)
# ----------------------------------------------------------------------------
RNG = np.random.default_rng(1234)


def kick(big=1.0):
    t = t_arr(0.55)
    f = 45 + 110 * np.exp(-t / 0.035)
    ph = 2 * np.pi * np.cumsum(f) / SR
    x = np.sin(ph) * np.exp(-t / (0.22 * big))
    click = RNG.standard_normal(len(t)) * np.exp(-t / 0.003) * 0.3
    return np.tanh(1.8 * (x + click)) * 0.9


def clap():
    t = t_arr(0.35)
    n = RNG.standard_normal(len(t))
    e = np.zeros(len(t))
    for d in (0.0, 0.011, 0.022):
        e += (t >= d) * np.exp(-np.clip(t - d, 0, None) / 0.012)
    e += np.exp(-t / 0.09) * 0.6
    x = sos_filter(n * e, "bandpass", [900, 6000])
    tone = np.sin(2 * np.pi * 190 * t) * np.exp(-t / 0.04) * 0.4
    return (x * 1.6 + tone) * 0.8


def hat(open_=False):
    t = t_arr(0.25 if open_ else 0.06)
    n = RNG.standard_normal(len(t))
    x = sos_filter(n, "highpass", 7500)
    return x * np.exp(-t / (0.07 if open_ else 0.012)) * 0.35


def cowbell(m, dur=0.22):
    t = t_arr(dur)
    f = midi_hz(m)
    x = signal.square(2 * np.pi * f * t, 0.5) * 0.6 + signal.square(2 * np.pi * f * 1.4829 * t, 0.5) * 0.4
    x = sos_filter(x, "bandpass", [f * 0.9, min(f * 4.5, 15000)])
    return x * np.exp(-t / 0.085) * 0.55


def bass808(f, dur, glide_from=None, drive=2.6):
    t = t_arr(dur)
    if glide_from:
        fr = f + (glide_from - f) * np.exp(-t / 0.06)
    else:
        fr = np.full(len(t), f)
    ph = 2 * np.pi * np.cumsum(fr) / SR
    x = np.sin(ph) * env_ar(len(t), 0.003, min(0.08, dur * 0.4)) * np.exp(-t / 1.4)
    return np.tanh(drive * x) / np.tanh(drive) * 0.8


def pad(chord, dur):
    t = t_arr(dur)
    x = np.zeros(len(t))
    for m in chord:
        for det in (-0.12, 0.0, 0.13):
            f = midi_hz(m + det)
            x += signal.sawtooth(2 * np.pi * f * t + RNG.uniform(0, 6.28))
    x = sos_filter(x, "lowpass", 1100) / (len(chord) * 3)
    return x * env_ar(len(t), 0.25, 0.4)


def riser(dur, f0=200, f1=2400):
    t = t_arr(dur)
    p = t / dur
    n = RNG.standard_normal((len(t), 2))
    out = np.zeros_like(n)
    hop = 2048
    for i in range(0, len(t), hop):          # time-varying bandpass in blocks
        fc = f0 * (f1 / f0) ** p[i]
        seg = n[max(0, i - 512): i + hop]
        y = sos_filter(seg, "bandpass", [fc * 0.6, min(fc * 1.8, 20000)])
        out[i: i + hop] = y[-len(out[i: i + hop]):]
    tone_f = 110 * 2 ** (3 * p)
    tone = np.sin(2 * np.pi * np.cumsum(tone_f) / SR) * 0.25
    e = p ** 2.2
    return (out * 0.9 + tone[:, None]) * e[:, None] * 0.7


def reverse_cymbal(dur):
    t = t_arr(dur)
    n = sos_filter(RNG.standard_normal((len(t), 2)), "highpass", 4000)
    return n * ((t / dur) ** 3)[:, None] * 0.45


def whoosh(dur=0.35, up=True):
    t = t_arr(dur)
    p = t / dur
    n = RNG.standard_normal((len(t), 2))
    out = np.zeros_like(n)
    hop = 1024
    for i in range(0, len(t), hop):
        q = p[i] if up else 1 - p[i]
        fc = 300 * (12 ** q)
        seg = n[max(0, i - 512): i + hop]
        y = sos_filter(seg, "bandpass", [fc * 0.5, min(fc * 2.0, 20000)])
        out[i: i + hop] = y[-len(out[i: i + hop]):]
    e = np.sin(np.pi * p) ** 1.5
    return out * e[:, None] * 0.8


def impact(strength=1.0):
    t = t_arr(2.4)
    f = 32 + 60 * np.exp(-t / 0.08)
    sub = np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t / 0.7)
    crack = sos_filter(RNG.standard_normal(len(t)), "lowpass", 5000) * np.exp(-t / 0.05)
    metal = sum(np.sin(2 * np.pi * fr * t) * np.exp(-t / d) for fr, d in
                ((313, 0.5), (487, 0.35), (811, 0.25), (1273, 0.18))) * 0.12
    x = np.tanh(1.5 * (sub * 1.0 + crack * 0.7 + metal)) * 0.9
    return x * strength


def text_hit():
    t = t_arr(0.18)
    n = sos_filter(RNG.standard_normal(len(t)), "bandpass", [1500, 9000]) * np.exp(-t / 0.02)
    thump = np.sin(2 * np.pi * (70 + 120 * np.exp(-t / 0.02)) * t) * np.exp(-t / 0.06)
    return (n * 0.5 + thump * 0.6) * 0.6


def blip(f=1800):
    t = t_arr(0.05)
    return np.sin(2 * np.pi * f * t) * np.exp(-t / 0.012) * 0.25


# ----------------------------------------------------------------------------
# Score
# ----------------------------------------------------------------------------
CHORDS = {  # A minor: Am, F, G, Em (pad voicing, 808 root)
    "Am": ([57, 60, 64], midi_hz(33)),
    "F": ([53, 57, 60], midi_hz(29)),
    "G": ([55, 59, 62], midi_hz(31)),
    "Em": ([52, 55, 59], midi_hz(28)),
}
PROG = ["Am", "Am", "F", "G"]
COWBELL = [  # (step in 2-bar phrase, midi)
    (0, 76), (3, 72), (6, 69), (8, 76), (10, 74), (12, 72), (14, 71),
    (16, 72), (19, 69), (22, 64), (24, 69), (26, 71), (28, 72), (29, 71), (30, 69),
]


def section_at(t):
    if t < 3.0:
        return "hook"
    if t < 9.0:
        return "intro"
    if 16.5 <= t < 17.5:
        return "break"
    if t < 21.0:
        return "drop"
    if t < 25.0:
        return "tension"
    if t < 27.5:
        return "climax"
    if t < 29.0:
        return "breathe"
    if t < 31.0:
        return "climax"
    if t < 36.0:
        return "end"
    return "tail"


def build_score():
    n = int(TOTAL * SR)
    drums = np.zeros((n, 2))
    bass = np.zeros((n, 2))
    melo = np.zeros((n, 2))
    padb = np.zeros((n, 2))
    sfx = np.zeros((n, 2))

    K = {"hook": [], "intro": [0, 8, 11], "drop": [0, 6, 10], "tension": [0, 8],
         "climax": [0, 3, 6, 10, 11, 14], "breathe": [], "end": [0, 8, 10], "break": [], "tail": []}
    C = {"intro": [12], "drop": [4, 12], "tension": [4, 12], "climax": [4, 12], "end": [12]}
    HAT = {"hook": 4, "intro": 2, "drop": 1, "tension": 2, "climax": 1, "breathe": 4, "end": 2}

    # grid: bars start on odd seconds (1, 3, 5 ...); steps every 16th from t=0
    nsteps = int(TOTAL / STEP)
    for s in range(nsteps):
        t = s * STEP
        sec = section_at(t)
        bar_step = int(round((t - 1.0) / STEP)) % 16
        bar_idx = int((t - 1.0) // 2.0) if t >= 1.0 else -1
        if sec == "tail":
            continue
        if bar_step in K.get(sec, []):
            add(drums, kick(1.2 if sec == "climax" else 1.0), t, 0.95)
        if bar_step in C.get(sec, []):
            add(drums, clap(), t, 0.55 if sec != "end" else 0.4)
        hs = HAT.get(sec)
        if hs and bar_step % hs == 0:
            vel = 0.55 if bar_step % 4 == 0 else 0.35
            add(drums, hat(), t, vel * (0.6 if sec in ("hook", "breathe") else 1.0), pan=0.25)
        if sec in ("drop", "climax") and bar_idx % 2 == 1 and bar_step in (13, 14, 15):
            for k in range(2):  # 32nd-note hat roll
                add(drums, hat(), t + k * STEP / 2, 0.3, pan=-0.2)
        if sec in ("drop", "climax", "intro") and bar_step == 14:
            add(drums, hat(True), t, 0.25, pan=0.3)

        # 808 follows the kick in groove sections
        if sec in ("intro", "drop", "climax", "end", "tension") and bar_step in K.get(sec, [0]):
            ch = PROG[bar_idx % 4] if bar_idx >= 0 else "Am"
            root = CHORDS[ch][1]
            ks = K[sec]
            nxt = [k for k in ks if k > bar_step]
            dur = ((nxt[0] if nxt else 16) - bar_step) * STEP
            glide = root * 1.5 if (sec == "climax" and bar_step == 0) else None
            add(bass, bass808(root, dur + 0.02, glide, 3.2 if sec == "climax" else 2.6), t, 0.9)

        # phonk cowbell melody
        if sec in ("intro", "drop", "climax", "end"):
            ph_step = int(round((t - 1.0) / STEP)) % 32
            for st, m in COWBELL:
                if st == ph_step:
                    g = {"intro": 0.30, "drop": 0.42, "climax": 0.46, "end": 0.26}[sec]
                    add(melo, cowbell(m), t, g, pan=-0.15)
                    if sec == "climax":
                        add(melo, cowbell(m + 12), t, 0.16, pan=0.3)

    # pads per bar
    for b in range(-1, 18):
        t0 = 1.0 + 2 * b
        if t0 >= 36.0:
            break
        ch = PROG[b % 4] if b >= 0 else "Am"
        start = max(0.0, t0)
        dur = 2.0 if b >= 0 else 1.0
        g = 0.22 if section_at(start + 0.01) in ("hook", "tension", "breathe", "end") else 0.14
        add(padb, pad(CHORDS[ch][0], dur + 0.4), start, g)
    # hook drone
    add(padb, sos_filter(bass808(midi_hz(33), 3.0, drive=1.2), "lowpass", 300), 0.0, 0.45)
    # tension: hat 16ths accelerate + snare roll 23 -> 24.85
    t = 23.0
    while t < 24.85:
        p = (t - 23.0) / 1.85
        add(drums, clap(), t, 0.15 + 0.35 * p)
        t += STEP if p < 0.5 else (STEP / 2 if p < 0.85 else STEP / 4)
    # breathe: low 808 sustain
    add(bass, bass808(CHORDS["F"][1], 1.5, drive=1.8), 27.5, 0.6)
    # end card: final ring-out of the pad after the final hit
    add(padb, pad(CHORDS["Am"][0], 1.2), 36.0, 0.18)

    # ---- SFX ----
    for ti, s in IMPACTS:
        add(sfx, impact(s), ti, 0.55)
    for ti, d in WHIPS:
        add(sfx, whoosh(0.32, up=d > 0), ti - 0.2, 0.55, pan=0.4 * d)
    add(sfx, riser(1.5), 1.5, 0.55)            # hook -> title
    add(sfx, riser(1.5), 7.5, 0.45)            # into the drop
    add(sfx, reverse_cymbal(0.9), 16.6, 0.5)   # victory break -> back in
    add(sfx, riser(1.0), 20.0, 0.35)           # into rocket fire
    add(sfx, riser(3.85), 21.0, 0.6)           # rocket flight tension
    add(sfx, reverse_cymbal(0.7), 28.3, 0.45)  # breathe -> victory
    add(sfx, riser(1.2), 29.8, 0.3)            # into end card
    for ti in (0.12, 9.04, 11.04, 12.54, 14.5, 28.5):   # caption slams
        add(sfx, text_hit(), ti, 0.5)
    # freeze-frame "tape stop" accent
    add(sfx, whoosh(0.35, up=False), 14.5, 0.4)
    # code reveal blips
    for i in range(len(MAP_CODE)):
        add(sfx, blip(1600 + 90 * i), 31.62 + i * 0.028, 0.5, pan=-0.6 + 1.2 * i / len(MAP_CODE))

    ir = make_ir()
    drums = reverb(drums, ir, 0.10)
    melo = reverb(melo, ir, 0.22)
    padb = reverb(padb, ir, 0.30)
    sfx = reverb(sfx, ir, 0.18)
    bass = sos_filter(bass, "highpass", 28)  # control the sub
    music = drums * 0.9 + bass * 0.75 + melo * 0.85 + padb * 0.9
    # silence gaps for punch: 2.92-3.0 and 24.85-25.0
    for a, b in ((2.92, 3.0), (24.85, 25.0)):
        i0, i1 = int(a * SR), int(b * SR)
        music[i0:i1] *= np.linspace(1, 0, i1 - i0)[:, None] ** 3
    # fade the groove out into the final hit
    i36 = int(36.0 * SR)
    music[i36:] *= np.linspace(1, 0, len(music) - i36)[:, None] ** 2
    return music, sfx


# ----------------------------------------------------------------------------
# Voice-over
# ----------------------------------------------------------------------------
def read_wav_mono(path):
    with wave.open(path) as w:
        sr = w.getframerate()
        a = np.frombuffer(w.readframes(w.getnframes()), np.int16).astype(np.float64) / 32768
        if w.getnchannels() == 2:
            a = a.reshape(-1, 2).mean(1)
    return a, sr


def trim_silence(a, thr=0.012, pad_s=0.03):
    idx = np.where(np.abs(a) > thr)[0]
    if not len(idx):
        return a
    p = int(pad_s * SR)
    return a[max(0, idx[0] - p): idx[-1] + p]


def compress(x, thr_db=-20, ratio=3.0, att=0.004, rel=0.09, makeup_db=0):
    """Feed-forward peak compressor (one-pole release follower)."""
    thr = 10 ** (thr_db / 20)
    er = math.exp(-1 / (rel * SR))
    env = signal.lfilter([1 - er], [1, -er], np.abs(x))
    env = np.maximum(env, 1e-9)
    gain = np.where(env > thr, (thr * (env / thr) ** (1 / ratio)) / env, 1.0)
    return x * gain * 10 ** (makeup_db / 20)


def deess(x, lo=5000, hi=10000, thr_db=-30, ratio=4.0):
    band = sos_filter(x, "bandpass", [lo, hi], 2)
    rest = x - band
    return rest + compress(band, thr_db, ratio, 0.001, 0.04)


def process_vo(a):
    a = sos_filter(a, "highpass", 85)
    a = peaking(a, 220, -2.0, 1.0)       # clear mud
    a = peaking(a, 3200, 3.0, 0.9)       # presence
    a = peaking(a, 110, 1.5, 0.8)        # a bit of chest
    a = compress(a, -22, 3.0, 0.004, 0.1)
    a = deess(a)
    a = np.tanh(a * 1.3) / np.tanh(1.3)  # gentle saturation
    return a / (np.abs(a).max() + 1e-9) * 0.89


def synth_vo(voices_dir, work):
    from piper import PiperVoice, SynthesisConfig
    model = os.path.join(voices_dir, "en_US-joe-medium.onnx")
    voice = PiperVoice.load(model)
    vo_dir = os.path.join(work, "vo")
    os.makedirs(vo_dir, exist_ok=True)
    track = np.zeros(int(TOTAL * SR))
    placed = []
    prev_end = 0.0
    for i, (t0, text, ls) in enumerate(VO_LINES):
        p = os.path.join(vo_dir, f"line_{i:02d}.wav")
        with wave.open(p, "wb") as w:
            voice.synthesize_wav(text, w, syn_config=SynthesisConfig(
                length_scale=ls, noise_scale=0.6, noise_w_scale=0.7))
        a, sr = read_wav_mono(p)
        a = signal.resample_poly(a, SR // math.gcd(SR, sr), sr // math.gcd(SR, sr))
        a = trim_silence(a)
        a = process_vo(a)
        dur = len(a) / SR
        if t0 < prev_end + 0.05:
            log(f"  WARN VO line {i} overlaps previous ({t0:.2f} < {prev_end:.2f}), shifting")
            t0 = prev_end + 0.05
        i0 = int(t0 * SR)
        track[i0:i0 + len(a)] += a[: len(track) - i0]
        placed.append(dict(start=round(t0, 3), end=round(t0 + dur, 3), text=text))
        prev_end = t0 + dur
        log(f"  VO {t0:6.2f}-{t0 + dur:6.2f}  {text}")
    # subtle room
    st = reverb(track, make_ir(0.6, 0.12, seed=3, lp=7000), 0.07)
    return st, placed


# ----------------------------------------------------------------------------
# Original gameplay audio, remapped with the same EDL
# ----------------------------------------------------------------------------
def load_src_audio(path):
    raw = run(["ffmpeg", "-v", "error", "-i", path, "-vn", "-ac", "2", "-ar", str(SR),
               "-f", "f32le", "-"], capture_output=True).stdout
    return np.frombuffer(raw, np.float32).reshape(-1, 2).astype(np.float64)


def seg_map(seg, t):
    ks = seg["keys"]
    return np.interp(t, [k[0] for k in ks], [k[1] for k in ks])


def game_audio(srcs):
    out = np.zeros((int(TOTAL * SR), 2))
    for seg in SEGMENTS:
        if seg.get("endcard"):
            continue
        a0, a1 = seg["keys"][0][0], seg["keys"][-1][0]
        i0, i1 = int(a0 * SR), int(a1 * SR)
        t = np.arange(i0, i1) / SR
        st = seg_map(seg, t)
        src = srcs[seg["src"]]
        idx = st * SR
        y = np.stack([np.interp(idx, np.arange(len(src)), src[:, c]) for c in range(2)], 1)
        # gain: inside narration-free windows only, muted on freeze frames
        g = np.zeros(len(t))
        for w0, w1 in GAME_AUDIO_WINDOWS[seg["src"]]:
            g = np.maximum(g, np.clip(np.minimum(st - w0, w1 - st) / 0.06, 0, 1))
        rate = np.gradient(st) * SR
        g *= np.clip(rate / 0.3, 0, 1)
        n = len(t)
        f = min(int(0.012 * SR), n // 2)
        g[:f] *= np.linspace(0, 1, f)
        g[-f:] *= np.linspace(1, 0, f)
        out[i0:i1] += y * g[:, None]
    return out


def envelope(x, att=0.03, rel=0.3):
    lvl = np.abs(x).max(1) if x.ndim == 2 else np.abs(x)
    ea, er = math.exp(-1 / (att * SR)), math.exp(-1 / (rel * SR))
    env = np.zeros_like(lvl)
    e = 0.0
    # decimated follower for speed
    hop = 64
    for i in range(0, len(lvl), hop):
        v = lvl[i:i + hop].max()
        c = ea ** hop if v > e else er ** hop
        e = c * e + (1 - c) * v
        env[i:i + hop] = e
    return env


def ffmpeg_write_wav(x, path, codec="pcm_s24le"):
    x = np.ascontiguousarray(x.astype(np.float32))
    run(["ffmpeg", "-v", "error", "-y", "-f", "f32le", "-ar", str(SR), "-ac", str(x.shape[1] if x.ndim == 2 else 1),
         "-i", "-", "-c:a", codec, path], input=x.tobytes())


def build_audio(args, work, out_dir):
    log("[audio] voice-over")
    vo, placed = synth_vo(args.voices, work)
    log("[audio] score + sfx")
    music, sfx = build_score()
    log("[audio] gameplay audio")
    srcs = {"sc": load_src_audio(args.scrims), "t1": load_src_audio(args.timeline)}
    game = game_audio(srcs)
    game = sos_filter(game, "highpass", 60)

    # duck music (and game audio) under narration: ~ -9 dB
    env = envelope(vo, 0.02, 0.35)
    env = env / (env.max() + 1e-9)
    duck = 1.0 - 0.75 * np.clip(env * 3.0, 0, 1)     # ~ -12 dB under narration
    duck_g = 1.0 - 0.6 * np.clip(env * 3.0, 0, 1)

    mix = music * 0.45 * duck[:, None] + sfx * 0.55 + game * 1.0 * duck_g[:, None] + vo * 1.25
    # final tail fade
    nf = int(0.35 * SR)
    mix[-nf:] *= np.linspace(1, 0, nf)[:, None] ** 2
    # soft bus clip safety before loudnorm
    mix = np.tanh(mix * 0.9) / 0.9

    ffmpeg_write_wav(vo, os.path.join(out_dir, "voiceover.wav"))
    pre = os.path.join(work, "mix_pre.wav")
    ffmpeg_write_wav(mix, pre, "pcm_f32le")
    for name, stem in (("stem_music.wav", music * 0.45 * duck[:, None]), ("stem_sfx.wav", sfx * 0.55),
                       ("stem_game.wav", game * 1.0 * duck_g[:, None]), ("stem_vo.wav", vo * 1.25)):
        ffmpeg_write_wav(stem, os.path.join(work, name), "pcm_f32le")
    ffmpeg_write_wav(sfx * 0.55, os.path.join(ASSETS, "sfx_layer.wav"), "pcm_s16le")
    ffmpeg_write_wav(music * 0.45, os.path.join(ASSETS, "music_original_instrumental.wav"), "pcm_s16le")

    # two-pass loudnorm -> -14 LUFS, -1.5 dBTP
    r = subprocess.run(["ffmpeg", "-hide_banner", "-i", pre, "-af",
                        "loudnorm=I=-14:TP=-1.5:LRA=11:print_format=json", "-f", "null", "-"],
                       capture_output=True, text=True)
    js = json.loads(r.stderr[r.stderr.rfind("{"): r.stderr.rfind("}") + 1])
    af = ("loudnorm=I=-14:TP=-1.5:LRA=11:linear=true:"
          f"measured_I={js['input_i']}:measured_TP={js['input_tp']}:measured_LRA={js['input_lra']}:"
          f"measured_thresh={js['input_thresh']}:offset={js['target_offset']},"
          "alimiter=limit=0.84:attack=3:release=40:level=false")
    final = os.path.join(out_dir, "final_audio.wav")
    run(["ffmpeg", "-v", "error", "-y", "-i", pre, "-af", af, "-ar", str(SR), "-c:a", "pcm_s24le", final])
    with open(os.path.join(work, "vo_placement.json"), "w") as f:
        json.dump(placed, f, indent=1)
    return final, placed


# ============================================================================
# GRAPHICS
# ============================================================================
def font(path, size):
    return ImageFont.truetype(path, size)


def text_width(fnt, text, tracking):
    w = 0
    for i, ch in enumerate(text):
        w += fnt.getlength(ch) + (tracking if i < len(text) - 1 else 0)
    return w


def render_lines(lines, max_w=920, gap=0.02, glow=True):
    """lines: [(text, rgb, size, font_path, tracking)] -> BGRA numpy image"""
    rendered = []
    for text, rgb, size, fpath, tr in lines:
        fnt = font(fpath, size)
        tw = text_width(fnt, text, tr)
        if tw > max_w:  # auto-fit
            size = int(size * max_w / tw)
            fnt = font(fpath, size)
            tw = text_width(fnt, text, tr)
        asc, desc = fnt.getmetrics()
        rendered.append((text, rgb, size, fnt, tr, tw, asc + desc))
    pad = 60
    bw = int(max(r[5] for r in rendered)) + pad * 2
    bh = int(sum(r[6] for r in rendered) * (1 + gap)) + pad * 2
    mask_fill = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
    mask_all = Image.new("L", (bw, bh), 0)
    d = ImageDraw.Draw(mask_fill)
    dm = ImageDraw.Draw(mask_all)
    y = pad
    for text, rgb, size, fnt, tr, tw, lh in rendered:
        x = (bw - tw) / 2
        for ch in text:
            d.text((x, y), ch, font=fnt, fill=rgb + (255,))
            dm.text((x, y), ch, font=fnt, fill=255)
            x += fnt.getlength(ch) + tr
        y += lh * (1 + gap)
    base = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
    # drop shadow
    sh = mask_all.filter(ImageFilter.GaussianBlur(10))
    shadow = Image.new("RGBA", (bw, bh), (0, 0, 0, 0))
    shadow.putalpha(sh.point(lambda v: int(v * 0.85)))
    base = Image.alpha_composite(base, shadow)
    if glow:
        g = mask_all.filter(ImageFilter.GaussianBlur(18))
        glow_l = Image.new("RGBA", (bw, bh), CYAN_RGB + (0,))
        glow_l.putalpha(g.point(lambda v: int(v * 0.55)))
        base = Image.alpha_composite(base, glow_l)
    base = Image.alpha_composite(base, mask_fill)
    arr = np.array(base)
    return arr[..., [2, 1, 0, 3]].copy()  # RGBA -> BGRA


def gradient_band(h=760, strength=0.62):
    y = np.linspace(-1, 1, h)
    a = (1 - np.abs(y) ** 2) * strength
    img = np.zeros((h, W, 4), np.uint8)
    img[..., 3] = (a[:, None] * 255).astype(np.uint8)
    img[..., :3] = (8, 6, 4)
    return img


def rounded_panel(w, h, r, fill_rgba, border_rgb=None, bw=4, glow=True):
    pad = 50
    im = Image.new("RGBA", (w + 2 * pad, h + 2 * pad), (0, 0, 0, 0))
    if glow and border_rgb:
        g = Image.new("L", im.size, 0)
        ImageDraw.Draw(g).rounded_rectangle([pad, pad, pad + w, pad + h], r, outline=255, width=bw + 6)
        g = g.filter(ImageFilter.GaussianBlur(16))
        gl = Image.new("RGBA", im.size, border_rgb + (0,))
        gl.putalpha(g.point(lambda v: int(v * 0.8)))
        im = Image.alpha_composite(im, gl)
    layer = Image.new("RGBA", im.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    d.rounded_rectangle([pad, pad, pad + w, pad + h], r, fill=fill_rgba,
                        outline=(border_rgb + (255,)) if border_rgb else None, width=bw)
    im = Image.alpha_composite(im, layer)
    arr = np.array(im)
    return arr[..., [2, 1, 0, 3]].copy()


def hline(w, thickness=4, rgb=CYAN_RGB):
    pad = 30
    im = Image.new("RGBA", (w + 2 * pad, thickness + 2 * pad), (0, 0, 0, 0))
    g = Image.new("L", im.size, 0)
    ImageDraw.Draw(g).rectangle([pad, pad, pad + w, pad + thickness], fill=255)
    gb = g.filter(ImageFilter.GaussianBlur(8))
    gl = Image.new("RGBA", im.size, rgb + (0,))
    gl.putalpha(gb)
    im = Image.alpha_composite(im, gl)
    solid = Image.new("RGBA", im.size, rgb + (0,))
    solid.putalpha(g)
    im = Image.alpha_composite(im, solid)
    arr = np.array(im)
    return arr[..., [2, 1, 0, 3]].copy()


def ease_out(x):
    x = min(max(x, 0.0), 1.0)
    return 1 - (1 - x) ** 3


def ease_out_back(x, s=1.6):
    x = min(max(x, 0.0), 1.0) - 1
    return 1 + (s + 1) * x ** 3 + s * x ** 2


class Overlay:
    def __init__(self, img, cx, cy, t0, t1, anim="slam", scale0=1.35, fade_out=0.12,
                 wipe=0.0, delay_alpha=0.06, pulse=False, slide=0, scale_x_anim=False):
        self.img, self.cx, self.cy, self.t0, self.t1 = img, cx, cy, t0, t1
        self.anim, self.scale0, self.fade_out, self.wipe = anim, scale0, fade_out, wipe
        self.delay_alpha, self.pulse, self.slide, self.scale_x_anim = delay_alpha, pulse, slide, scale_x_anim

    def draw(self, frame, t):
        if not (self.t0 <= t < self.t1):
            return
        u, r = t - self.t0, self.t1 - t
        alpha = min(u / self.delay_alpha, 1.0) if self.delay_alpha > 0 else 1.0
        if self.fade_out > 0:
            alpha *= min(r / self.fade_out, 1.0)
        sx = sy = 1.0
        dx = 0.0
        if self.anim == "slam":
            s = 1 + (self.scale0 - 1) * (1 - ease_out(u / 0.16))
            sx = sy = s
        elif self.anim == "pop":
            s = 0.6 + 0.4 * ease_out_back(u / 0.28)
            sx = sy = s
        elif self.anim == "slide":
            dx = self.slide * (1 - ease_out(u / 0.3))
        if self.scale_x_anim:
            sx = max(0.02, ease_out(u / 0.4))
            sy = 1.0
        if r < self.fade_out:  # tiny push on exit
            k = 1 + 0.06 * (1 - r / self.fade_out)
            sx *= k
            sy *= k
        if self.pulse:
            ph = ((t - self.t0) % BEAT) / BEAT
            k = 1 + 0.035 * math.exp(-ph * 6)
            sx *= k
            sy *= k
        img = self.img
        if self.wipe > 0:
            frac = ease_out(u / self.wipe)
            cut = int(img.shape[1] * frac)
            img = img.copy()
            img[:, cut:, 3] = 0
        if abs(sx - 1) > 1e-3 or abs(sy - 1) > 1e-3:
            nw, nh = max(2, int(img.shape[1] * sx)), max(2, int(img.shape[0] * sy))
            img = cv2.resize(img, (nw, nh), interpolation=cv2.INTER_LINEAR)
        blit(frame, img, self.cx + dx, self.cy, alpha)


def blit(frame, img, cx, cy, alpha=1.0):
    h, w = img.shape[:2]
    x0, y0 = int(round(cx - w / 2)), int(round(cy - h / 2))
    fx0, fy0 = max(0, x0), max(0, y0)
    fx1, fy1 = min(W, x0 + w), min(H, y0 + h)
    if fx1 <= fx0 or fy1 <= fy0 or alpha <= 0:
        return
    sub = img[fy0 - y0: fy1 - y0, fx0 - x0: fx1 - x0]
    a = sub[..., 3:4].astype(np.float32) * (alpha / 255.0)
    roi = frame[fy0:fy1, fx0:fx1].astype(np.float32)
    frame[fy0:fy1, fx0:fx1] = (roi * (1 - a) + sub[..., :3].astype(np.float32) * a).astype(np.uint8)


def build_overlays():
    A, I = FONT_ANTON, FONT_INTER
    ov = []
    save = {}
    LOW = 1330   # lower-third caption centre (inside TikTok/Reels safe zone)
    band = gradient_band()

    HIGH = 560   # upper third: keeps the in-game "ELIMINATED" banner (y~1330) visible
    def caption(lines, t0, t1, anim="slam", cy=LOW, **kw):
        img = render_lines(lines)
        ov.append(Overlay(band, W / 2, cy, t0, t1, anim="fade", delay_alpha=0.1, fade_out=0.15))
        ov.append(Overlay(img, W / 2, cy, t0, t1, anim=anim, **kw))
        return img

    save["caption_think_youre_ready"] = caption(
        [("THINK YOU'RE", WHITE_RGB, 118, A, 4), ("READY?", CYAN_RGB, 200, A, 6)], 0.12, 2.92, cy=HIGH)
    # title reveal
    title = render_lines([("REALISTIC", CYAN_RGB, 176, A, 10), ("SCRIMS", WHITE_RGB, 300, A, 12)])
    save["title_realistic_scrims"] = title
    ov.append(Overlay(title, W / 2, 900, 3.0, 4.95, anim="slam", scale0=1.6, fade_out=0.18))
    bar = hline(760, 5)
    ov.append(Overlay(bar, W / 2, 620, 3.05, 4.95, anim="fade", scale_x_anim=True, fade_out=0.18))
    ov.append(Overlay(bar, W / 2, 1190, 3.05, 4.95, anim="fade", scale_x_anim=True, fade_out=0.18))
    save["caption_tagline"] = caption(
        [("YOUR MECHANICS.", WHITE_RGB, 104, A, 4), ("YOUR TEST.", CYAN_RGB, 150, A, 6)], 5.12, 8.92,
        anim="slide", slide=-90, delay_alpha=0.18)
    for word, t0, t1, cy in (("BUILD.", 9.04, 10.94, LOW), ("EDIT.", 11.04, 12.44, LOW),
                             ("AIM.", 12.54, 13.44, LOW), ("ELIMINATE.", 14.50, 15.75, HIGH)):
        save[f"caption_{word.strip('.').lower()}"] = caption([(word, WHITE_RGB, 210, A, 8)], t0, t1,
                                                             cy=cy, scale0=1.5)
    save["caption_prove_yourself"] = caption(
        [("PROVE", WHITE_RGB, 150, A, 6), ("YOURSELF.", CYAN_RGB, 190, A, 8)], 28.52, 30.92, scale0=1.5)

    # ---- END CARD ----
    e_title = render_lines([("REALISTIC", CYAN_RGB, 160, A, 10), ("SCRIMS", WHITE_RGB, 270, A, 12)])
    save["endcard_title"] = e_title
    ov.append(Overlay(e_title, W / 2, 640, 31.0, TOTAL + 1, anim="slam", scale0=1.5, fade_out=0))
    label = render_lines([("MAP CODE", ICE_RGB, 58, I, 14)], glow=False)
    save["endcard_label"] = label
    ov.append(Overlay(label, W / 2, 990, 31.35, TOTAL + 1, anim="slide", slide=0, delay_alpha=0.2, fade_out=0))
    l2 = hline(200, 4)
    ov.append(Overlay(l2, W / 2 - 330, 992, 31.35, TOTAL + 1, anim="fade", scale_x_anim=True, fade_out=0))
    ov.append(Overlay(l2, W / 2 + 330, 992, 31.35, TOTAL + 1, anim="fade", scale_x_anim=True, fade_out=0))
    panel = rounded_panel(960, 200, 28, (6, 10, 16, 215), CYAN_RGB, 5)
    save["endcard_code_panel"] = panel
    ov.append(Overlay(panel, W / 2, 1140, 31.5, TOTAL + 1, anim="pop", fade_out=0, delay_alpha=0.1))
    code = render_lines([(MAP_CODE, WHITE_RGB, 150, A, 6)], max_w=880, glow=True)
    save["endcard_code"] = code
    ov.append(Overlay(code, W / 2, 1140, 31.62, TOTAL + 1, anim="fade", wipe=0.38, delay_alpha=0.01, fade_out=0))
    btn = rounded_panel(560, 140, 70, CYAN_RGB + (255,), CYAN_RGB, 2)
    btn_txt = render_lines([("PLAY NOW", (5, 12, 20), 100, A, 8)], glow=False)
    bh, bw = btn_txt.shape[:2]
    comb = btn.copy()
    blit_rgba(comb, btn_txt)
    save["endcard_play_now"] = comb
    ov.append(Overlay(comb, W / 2, 1440, 32.3, TOTAL + 1, anim="pop", fade_out=0, delay_alpha=0.1, pulse=True))
    return ov, save


def blit_rgba(dst, src):
    """alpha-composite src (BGRA) centred onto dst (BGRA), in place."""
    h, w = src.shape[:2]
    H2, W2 = dst.shape[:2]
    y0, x0 = (H2 - h) // 2, (W2 - w) // 2
    ys, xs = max(0, -y0), max(0, -x0)
    y0c, x0c = max(0, y0), max(0, x0)
    sub = src[ys: ys + min(h, H2), xs: xs + min(w, W2)]
    hh, ww = sub.shape[:2]
    hh, ww = min(hh, H2 - y0c), min(ww, W2 - x0c)
    sub = sub[:hh, :ww].astype(np.float32)
    d = dst[y0c:y0c + hh, x0c:x0c + ww].astype(np.float32)
    a = sub[..., 3:4] / 255
    rgb = sub[..., :3] * a + d[..., :3] * (1 - a)
    al = sub[..., 3:4] + d[..., 3:4] * (1 - a)
    dst[y0c:y0c + hh, x0c:x0c + ww] = np.concatenate([rgb, al], 2).astype(np.uint8)


# ============================================================================
# VIDEO
# ============================================================================
class SegmentFrames:
    def __init__(self, path, t_lo, t_hi):
        ss = max(0.0, math.floor(t_lo * FPS - 2) / FPS)
        dur = (t_hi - ss) + 3 / FPS
        raw = run(["ffmpeg", "-v", "error", "-ss", f"{ss:.4f}", "-i", path, "-t", f"{dur:.4f}",
                   "-vf", "scale=in_color_matrix=bt709:in_range=tv:out_range=pc,format=bgr24",
                   "-f", "rawvideo", "-pix_fmt", "bgr24", "-"], capture_output=True).stdout
        self.frames = np.frombuffer(raw, np.uint8).reshape(-1, H, W, 3)
        self.first = int(math.ceil(ss * FPS - 1e-6))

    def get(self, t_src, blend):
        f = t_src * FPS - self.first
        n = len(self.frames)
        i0 = int(math.floor(f))
        frac = f - i0
        i0 = min(max(i0, 0), n - 1)
        if not blend or frac < 0.08 or i0 + 1 >= n:
            j = min(max(int(round(f)), 0), n - 1)
            return self.frames[j].copy()
        return cv2.addWeighted(self.frames[i0], 1 - frac, self.frames[i0 + 1], frac, 0)


def make_grade_lut():
    x = np.arange(256) / 255.0
    s = x * x * (3 - 2 * x)
    base = x * 0.62 + s * 0.38                      # contrast
    sh = (1 - x) ** 2.2
    b = np.clip(base + 0.035 * sh, 0, 1)            # cool shadows
    g = np.clip(base + 0.008 * sh, 0, 1)
    r = np.clip(base - 0.025 * sh, 0, 1)
    return [(c * 255).astype(np.uint8) for c in (b, g, r)]


def make_vignette(strength=0.30):
    yy, xx = np.mgrid[0:H, 0:W]
    d = np.sqrt(((xx - W / 2) / (W / 2)) ** 2 * 0.8 + ((yy - H / 2) / (H / 2)) ** 2)
    v = 1 - strength * np.clip(d - 0.45, 0, None) ** 1.6
    v = np.clip(v, 0, 1)
    return np.repeat((v * 255).astype(np.uint8)[..., None], 3, 2)


def decay(t, t0, dur):
    if t < t0 or t >= t0 + dur:
        return 0.0
    return math.exp(-4.5 * (t - t0) / dur)


def shake_xy(t, amp):
    return (amp * (math.sin(t * 91.3) * 0.6 + math.sin(t * 57.1 + 1.3) * 0.4),
            amp * (math.sin(t * 77.7 + 0.7) * 0.6 + math.sin(t * 43.9 + 2.1) * 0.4))


def render_video(args, work, out_video, stills=None):
    lut = make_grade_lut()
    vig = make_vignette()
    overlays, saved = build_overlays()
    gfx_dir = os.path.join(ASSETS, "graphics")
    os.makedirs(gfx_dir, exist_ok=True)
    for k, im in saved.items():
        cv2.imwrite(os.path.join(gfx_dir, f"{k}.png"), im)

    paths = {"sc": args.scrims, "t1": args.timeline}
    code_times, code_end = CODE_GROUP_TIMES, CODE_GROUP_END
    vp = os.path.join(work, "vo_placement.json")
    if os.path.exists(vp):
        with open(vp) as f:
            placed = json.load(f)
        code_times = [p["start"] for p in placed[-3:]]
        code_end = placed[-1]["end"] + 0.25
    cut_times = sorted({s["keys"][0][0] for s in SEGMENTS})
    impact_t = {t for t, _ in IMPACTS}

    enc = None
    if stills is None:
        enc = subprocess.Popen([
            "ffmpeg", "-v", "error", "-y", "-f", "rawvideo", "-pix_fmt", "bgr24", "-s", f"{W}x{H}",
            "-r", str(FPS), "-i", "-",
            "-vf", "scale=in_range=pc:out_color_matrix=bt709:out_range=tv,format=yuv420p",
            "-c:v", "libx264", "-preset", "slow", "-crf", "18", "-maxrate", "16M", "-bufsize", "32M",
            "-profile:v", "high", "-level", "4.2", "-g", "60", "-bf", "2",
            "-color_primaries", "bt709", "-color_trc", "bt709", "-colorspace", "bt709", "-color_range", "tv",
            "-movflags", "+faststart", out_video], stdin=subprocess.PIPE)

    nframes = int(round(TOTAL * FPS))
    frames_wanted = None
    if stills is not None:
        frames_wanted = {int(round(s * FPS)): s for s in stills}
    cache = {}
    for n in range(nframes):
        t = n / FPS
        if frames_wanted is not None and n not in frames_wanted:
            continue
        si = max(i for i, s in enumerate(SEGMENTS) if s["keys"][0][0] <= t + 1e-9)
        seg = SEGMENTS[si]
        if si not in cache:
            cache.clear()
            ks = seg["keys"]
            cache[si] = SegmentFrames(paths[seg["src"]], min(k[1] for k in ks), max(k[1] for k in ks))
        st = float(seg_map(seg, t))
        st_next = float(seg_map(seg, t + 1 / FPS))
        rate = (st_next - st) * FPS
        frame = cache[si].get(st, blend=(0.05 < rate < 0.92))
        seg_t0, seg_t1 = seg["keys"][0][0], seg["keys"][-1][0]
        u = (t - seg_t0) / (seg_t1 - seg_t0)

        # ---- camera: zoom / punch / shake / rotation ----
        z = seg.get("zoom", 1.0) * (1.0 + 0.035 * u)     # slow push-in per shot
        amp = 0.0
        rot = 0.0
        for ti, s in IMPACTS:
            k = decay(t, ti, 0.4)
            z += 0.09 * s * k
            amp += 16 * s * decay(t, ti, 0.32)
            rot += 0.6 * s * decay(t, ti, 0.3) * math.sin(t * 60)
        for ct in cut_times:
            if ct not in impact_t:
                z += 0.045 * decay(t, ct, 0.22)
        for a0, a1 in BEAT_BUMP_RANGES:
            if a0 <= t < a1:
                ph = ((t - a0) % BEAT)
                z += 0.014 * math.exp(-ph / 0.07)
        if seg.get("endcard"):
            z = 1.06 + 0.05 * u
        dx, dy = shake_xy(t, amp)
        z = max(z, 1.0 + 2 * (abs(dx) + abs(dy)) / W + 0.004)
        M = cv2.getRotationMatrix2D((W / 2, H / 2), rot, z)
        M[0, 2] += dx
        M[1, 2] += dy
        frame = cv2.warpAffine(frame, M, (W, H), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT101)

        # ---- whip transitions: directional motion blur around cuts ----
        for wt, d in WHIPS:
            dt = t - wt
            if -0.05 <= dt < 0.05:
                k = 1 - abs(dt + 0.5 / FPS) / 0.05
                L = int(10 + 110 * max(k, 0))
                ker = np.zeros((1, L), np.float32)
                ker[0, :] = 1.0 / L
                frame = cv2.filter2D(frame, -1, ker)
                shift = int(d * 70 * max(k, 0) * (1 if dt < 0 else -1))
                frame = np.roll(frame, shift, axis=1)

        # ---- grade ----
        b, g, r = cv2.split(frame)
        frame = cv2.merge([cv2.LUT(b, lut[0]), cv2.LUT(g, lut[1]), cv2.LUT(r, lut[2])])
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray3 = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
        sat = 1.12
        if seg.get("freeze") and seg["freeze"][0] <= t < seg["freeze"][1]:
            sat = 0.55
        frame = cv2.addWeighted(frame, sat, gray3, 1 - sat, 0)
        if seg.get("freeze") and seg["freeze"][0] <= t < seg["freeze"][1]:
            tint = np.full_like(frame, CYAN_BGR)
            frame = cv2.addWeighted(frame, 0.86, tint, 0.14, 0)

        # ---- section looks ----
        if "dim" in seg:
            k = min((t - seg_t0) / 0.25, 1.0) * min((seg_t1 - t) / 0.2, 1.0)
            if seg.get("blur"):  # soften busy background under the title
                small = cv2.resize(frame, (W // 3, H // 3), interpolation=cv2.INTER_AREA)
                soft = cv2.resize(cv2.GaussianBlur(small, (0, 0), 3), (W, H), interpolation=cv2.INTER_LINEAR)
                frame = cv2.addWeighted(frame, 1 - 0.85 * k, soft, 0.85 * k, 0)
            frame = cv2.convertScaleAbs(frame, alpha=1 - (1 - seg["dim"]) * k)
        if seg.get("endcard"):
            small = cv2.resize(frame, (W // 4, H // 4), interpolation=cv2.INTER_AREA)
            small = cv2.GaussianBlur(small, (0, 0), 5)
            frame = cv2.resize(small, (W, H), interpolation=cv2.INTER_LINEAR)
            frame = cv2.convertScaleAbs(frame, alpha=0.42)
            # cyan radial glow behind the code
            if "glow" not in cache:
                yy, xx = np.mgrid[0:H, 0:W]
                gl = np.exp(-(((xx - W / 2) / 520) ** 2 + ((yy - 1140) / 300) ** 2))
                cache["glow"] = (gl[..., None] * np.array(CYAN_BGR, np.float32) * 0.22).astype(np.uint8)
            pulse = 0.75 + 0.25 * math.exp(-((t - 31.0) % BEAT) / 0.12)
            frame = cv2.add(frame, (cache["glow"] * pulse).astype(np.uint8))

        frame = cv2.multiply(frame, vig, scale=1 / 255)

        # ---- chromatic aberration on impacts ----
        ca = max([decay(t, ti, 0.14) * s for ti, s in IMPACTS if ti > 0] + [0])  # clean first frame
        if ca > 0.05:
            sh = int(10 * ca)
            b, g, r = cv2.split(frame)
            frame = cv2.merge([np.roll(b, -sh, 1), g, np.roll(r, sh, 1)])

        # ---- overlays ----
        for o in overlays:
            o.draw(frame, t)
        # code-group highlight under each group as the VO reads it
        if t >= code_times[0] - 0.05 and t < code_end:
            gi = max(i for i, gt in enumerate(code_times) if t >= gt - 0.05)
            centers = [W / 2 - 300, W / 2, W / 2 + 300]
            x0 = int(centers[gi] - 120)
            k = min((t - code_times[gi] + 0.05) / 0.12, 1.0)
            cv2.rectangle(frame, (x0, 1212), (x0 + int(240 * k), 1220), CYAN_BGR, -1)

        # ---- flashes ----
        fl = max([decay(t, ti, 0.16) * s for ti, s in IMPACTS if ti > 0] + [0])
        if fl > 0.02:
            col = np.full_like(frame, 255)
            col[..., 0] = 255
            col[..., 1] = 245
            col[..., 2] = 225
            frame = cv2.addWeighted(frame, 1 - 0.55 * min(fl, 1), col, 0.55 * min(fl, 1), 0)
        # cut-to-black at the very end
        if t > TOTAL - 0.3:
            frame = cv2.convertScaleAbs(frame, alpha=max(0.0, (TOTAL - t) / 0.3))

        if enc:
            enc.stdin.write(frame.tobytes())
        else:
            cv2.imwrite(os.path.join(work, f"still_{t:06.2f}.png"), frame)
        if n % 120 == 0:
            log(f"  frame {n}/{nframes}  t={t:5.2f}  [{seg['name']}]")
    if enc:
        enc.stdin.close()
        if enc.wait() != 0:
            raise SystemExit("encoder failed")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scrims", required=True, help='"fortnite new video scrims.mp4"')
    ap.add_argument("--timeline", required=True, help='"Timeline 1.mp4"')
    ap.add_argument("--voices", required=True, help="dir containing en_US-joe-medium.onnx(+.json)")
    ap.add_argument("--out", default=HERE)
    ap.add_argument("--work", required=True, help="temp dir for intermediates")
    ap.add_argument("--stills", default=None, help="comma list of times: only render PNG stills")
    ap.add_argument("--audio-only", action="store_true")
    args = ap.parse_args()
    os.makedirs(args.work, exist_ok=True)
    os.makedirs(args.out, exist_ok=True)

    if args.stills:
        render_video(args, args.work, None, [float(s) for s in args.stills.split(",")])
        return
    final_audio, placed = build_audio(args, args.work, args.out)
    if args.audio_only:
        return
    vid = os.path.join(args.work, "video_only.mp4")
    log("[video] rendering")
    render_video(args, args.work, vid)
    out = os.path.join(args.out, "realistic_scrims_trailer.mp4")
    log("[mux]")
    run(["ffmpeg", "-v", "error", "-y", "-i", vid, "-i", final_audio, "-map", "0:v:0", "-map", "1:a:0",
         "-c:v", "copy", "-c:a", "aac", "-b:a", "256k", "-ar", str(SR), "-ac", "2",
         "-movflags", "+faststart", "-shortest", out])
    log("done:", out)


if __name__ == "__main__":
    main()
